import type { McpResourceDefinition } from "./types";

export const calibrationScenarioResources: readonly McpResourceDefinition[] = [
  {
    uri: "signalops://guide/scenarios/funnel-calibration",
    name: "guide.scenarios.funnel-calibration",
    description: "Concrete MCP playbook for turning a working manual/example bundle into generic product-funnel calibration.",
    mimeType: "application/json",
    read: async () => ({
      objective:
        "Use this scenario when a prior manual setup, example bundle, JSON asset, or admin-tuned configuration worked better than the current discovery/product flow.",
      startWith: [
        "Read the current runtime state first: system interests, compile status, LLM templates, channel bottlenecks, signal_candidate residuals, selected content, and discovery targets.",
        "Treat the reference bundle as calibration evidence, not canonical runtime truth and not code input.",
        "Do not assume the operator wants the reference domain rerun. If the request is to improve the system, produce reusable funnel-design rules and prompt/admin guidance before any product mutations.",
        "Compare the reference with current MCP state before creating new interests, templates, targets, or channels.",
      ],
      recommendedTools: {
        read: [
          "operator.funnel.audit",
          "operator.funnel.autoplan",
          "operator.funnel.iteration.recommend",
          "system_interests.list",
          "system_interests.read",
          "system_interests.compile_status.list",
          "templates.duplicates.audit",
          "llm_templates.list",
          "llm_templates.read",
          "channels.bottlenecks.summary",
          "channels.bottlenecks.list",
          "signal_candidates.residuals.summary",
          "signal_candidates.residuals.list",
          "content_items.list",
          "discovery.runs.list",
          "discovery.artifacts.list",
          "discovery.source_inventory.list",
          "discovery.policies.list",
          "operator.report.verify",
        ],
        writeFollowThrough: [
          "system_interests.create",
          "system_interests.update",
          "llm_templates.create",
          "llm_templates.update",
          "discovery.runs.create",
          "discovery.artifacts.create",
          "discovery.policies.activate",
          "channels.bulk_onboard.plan",
          "channels.bulk_onboard.apply",
          "maintenance.reindex.request",
        ],
      },
      extractFromReference: [
        "the objective and buyer/actor model: who creates the signal and what decision or pain it implies",
        "source capability classes and provider shapes that actually fed the funnel",
        "signal families, not just keywords",
        "positive prototypes and near-miss negative prototypes",
        "candidate uplift positive and negative cue groups",
        "allowed content kinds and strictness/review policy",
        "LLM review scope and guardrails for wrapper/noise pages",
        "provider types that require adapters or mapping instead of fake RSS/website rows",
      ],
      portableFunnelSpec: {
        requiredSections: [
          "objective and excluded outcomes",
          "actor/buyer model and evidence threshold",
          "signal families with positive prototypes",
          "near-miss negatives and must-not cues",
          "source capability matrix by provider shape",
          "working-noisy versus broken-source policy",
          "candidate or gray-zone recovery policy",
          "final selection and web-visibility proof gates",
          "observation budget for rare low-yield sources",
          "adapter or mapping gaps",
        ],
        sourceCapabilityMatrix: [
          "direct-intent sources: posts, notices, tenders, asks, support requests, or listings authored by the buyer or controlling organization",
          "context sources: funding, hiring, policy, incident, award, roadmap, or market signals that may create follow-up hypotheses but do not prove final demand alone",
          "community/hidden-signal sources: forum, social, Q&A, or discussion feeds that stay monitor/claim oriented unless the author and ask are clear",
          "directory/replacement sources: source lists, portals, sitemaps, newsletters, or related feeds used to expand acquisition breadth",
          "adapter-required sources: API-like, ATS, marketplace, repository, or authenticated sources that must not be disguised as RSS/website",
        ],
        consistencyChecks: [
          "Each active system interest should map to a named signal family, not a one-off keyword pile.",
          "Every positive cue family should have a paired near-miss negative family.",
          "For weak or short-form signals, item-level buyer/project evidence can be stronger than broad semantic similarity; configure candidate cue groups for buyer ask, project object, deliverable/scope, budget/timeline, and contact/procurement evidence instead of relying only on embedding proximity.",
          "Do not use single ambiguous words such as event, guide, fixed-price, hiring, or best practices as universal negatives; make them phrase-level negatives that only fire when buyer/project evidence is absent.",
          "LLM review prompts must use the specific interest/criterion as the authoritative frame, not broad topic similarity.",
          "High source semantic fit can extend observation, but cannot select or publish content.",
          "Low yield from a working rare-signal source is expected; transport/provider-shape failure is a repair problem.",
        ],
      },
      sessionFlow: [
        "Call operator.funnel.audit first when the client supports tools. The audit is read-only and returns portableFunnelSpec, DB-backed liveStateSummary, drift findings, and recommended MCP actions.",
        "First classify the current gap: source acquisition, provider-shape failure, transport bottleneck, projection/dedupe, semantic filtering, gray-zone hold, or LLM review behavior.",
        "Before running discovery, write down the portable funnel spec and use it as the checklist for interests, templates, source capability classes, adapter gaps, and proof.",
        "Use source expansion for source-pool gaps and template/interest tuning only for repeated downstream evidence patterns.",
        "For rare-signal funnels, prefer broad working source pools plus strict independent filtering; low yield alone is not a broken source.",
        "Coverage-first funnels should retain working noisy, low-yield, and negative-control useful channels as measured acquisition inventory. Only explicit operator action should disable a semantically plausible working channel; automatic handling should label, measure, slow cadence, repair technical blockers, or mark adapter/access requirements.",
        "Use discovery.source_families.coverage and operator.report.verify reportKind=source_family_balance to prove source-family balance before judging whether the funnel is complete.",
        "Use operator.funnel.autoplan for a read-only source-family/query/polling/repair/selection plan, then operator.funnel.iteration.recommend for the next bounded MCP action.",
        "If the gap is gray-zone hold after changed interests/templates or a failed full replay, follow operator.tuning.recommend and run bounded maintenance.reindex.request chunks with explicit docIds before changing selection criteria.",
        "Avoid broad hard gates early. Use must-have terms or time windows only when a marker is truly mandatory and replay/read-back proves recall is acceptable.",
        "For rare-signal baselines, treat empty must_have_terms and empty/null time_window_hours as the default starting point; recency goals belong in report/product-test acceptance unless the marker is truly part of the signal.",
        "Use negative cues and LLM guardrails to reject wrapper, seller-authored, navigation, directory, generic-advice, training, and jobs-only noise instead of adding broad positive hard gates.",
        "Selected content is the only web truth. If selected rows include context-only/noise, use operator.selection.precision_audit and selection tuning/replay to demote them; do not introduce a second public/private selected layer.",
        "When project-detail listings, support threads, or forum asks are short, tune candidateSignals so several independent item-level cues can recover the item into gray/LLM/hold even if semantic prototype similarity is below the usual near-threshold. Auto-selection from candidateSignals requires an explicit selection_profile_auto_select_mode plus clean evidence thresholds and veto checks.",
        "For marketplace/forum project pages, prefer positive cue groups like buyer_ask, project_object, deliverable_scope, budget_or_timeline, vendor_search, and integration_or_migration. Pair them with precise negatives such as seller-authored profile, category/navigation wrapper, generic advice without buyer project, and internal job opening without contractor/vendor ask.",
        "For executable search/aggregator lanes, treat search-ad click URLs, category/tag/search wrappers, ranking/list posts, seller-authored landing pages, generic how-to/why/guide signal_candidates, and jobs-only pages as acquisition noise unless the item itself contains buyer/project/vendor-search evidence.",
        "For weak-signal domains, prefer many technically working noisy sources plus strict downstream filtering. Repair transport/provider-shape bottlenecks separately from semantic quality, and do not loosen selected-content rules to compensate for low-yield sources.",
        "Do not mask API/social/ATS/StackExchange/GitHub/marketplace sources as RSS or website rows. Mark them adapter_required/api_mapping_required/needs_config or find validated alternatives.",
        "Use discovery.brief.preview, discovery.mega_loop.preview, discovery.candidates.create, discovery.probe.execute, discovery.understand.preview, discovery.route.preview, and source inventory reads to prove whether the funnel covers the places where the signal can actually appear.",
        "Use discovery.adapter_backlog.list/read and routing decisions to separate official/free, configured, access-gated, and unsupported acquisition lanes.",
        "Use Discovery vNext candidates and routing when closed or access-gapped source families need executable search coverage. Keep indirect/search channels acquisition-only unless a first-party source is actually onboarded. For local research without external keys or SearXNG, use ddgs_search.",
        "For marketplace/forum sources, check marketplace_extraction_quality before tuning: project-detail extraction must reject category/navigation/profile/listing-wrapper noise and preserve buyer/project fields when available.",
        "Apply one bounded change at a time, then verify affected entities and selection/web-visible counts through MCP.",
      ],
      whenToMutate: [
        "If the operator asks for research, design, or system improvement, return the portable funnel spec and recommended generic MCP/admin prompt changes without writing domain config.",
        "If the operator asks for a product test or calibration run, apply bounded MCP/admin config only after current state read-back and explicit scope is clear.",
        "If the reference shows API-like sources, record adapter requirements and alternative-finder work instead of forcing onboarding.",
      ],
      invariants: [
        "Reference bundles do not become runtime truth until applied through MCP/admin configuration and read back from the database.",
        "Domain-specific vocabulary belongs in templates, interests, targets, source config, and tests, not hardcoded runtime logic.",
        "Source health and vNext routing telemetry can improve acquisition and monitoring, but they must not directly select, rank, escalate, or publish content.",
        "Selected row counts and public content-item counts can differ because canonical/public projection and dedupe are separate product stages.",
      ],
      verifyAfterWrite: [
        "Read changed system interests or LLM templates back through MCP.",
        "If interest/template semantics changed for existing content, queue maintenance.reindex.request with jobKind=backfill and verify the job/run state. For retained DBs or timeout-prone replays, pass bounded payload.options.docIds chunks and parentReindexJobId/reason.",
        "For new or repaired sources, use channels.bulk_onboard.verify, fetch_runs.list, and channels.bottlenecks.summary/list.",
        "For source inventory or adapter backlog claims, call operator.report.verify with reportKind=source_family_balance or discovery_run.",
        "For coverage-first source-family claims, call operator.report.verify with reportKind=source_family_balance.",
        "For executable search lanes, call operator.report.verify with reportKind=indirect_search_execution.",
        "For marketplace/forum extraction quality, call operator.report.verify with reportKind=marketplace_extraction_quality.",
        "For final claims, call operator.report.verify with selection, source_bottleneck, channel_onboarding, or discovery_run as applicable.",
        "For calibration claims, call operator.report.verify with reportKind=funnel_calibration and includeSamples=true.",
      ],
    }),
  },
  {
    uri: "signalops://guide/scenarios/selection-calibration",
    name: "guide.scenarios.selection-calibration",
    description:
      "Concrete MCP playbook for zero selected signals, semantic rejection, missing LLM calls, and bounded selection calibration.",
    mimeType: "application/json",
    read: async () => ({
      objective:
        "Use this scenario when an external MCP client sees 0 selected signals, semantic_rejected/no_system_match, absent LLM spend, or confusing live Discovery failures and needs to classify the failing layer before changing configuration.",
      startWith: [
        "Read signalops://guide/playbooks/strict-next-steps and follow its read-back -> classify -> bounded write -> bounded replay -> verify sequence.",
        "Read admin.summary.get or signalops://admin/summary first.",
        "Read signalops://guide/reference/selection-evidence-semantics before interpreting hard gates, backfill counters, LLM spend, or gray-zone changes.",
        "Read signalops://guide/reference/hidden-signal-evidence-lanes before recommending must_have_terms, short_tokens_required, strictness changes, or candidateSignals cue repairs.",
        "Read operator.selection.dashboard and compare filterReasonBreakdown.filterRows to distinctCandidateCount before estimating candidate impact.",
        "Read signal_candidates.residuals.summary, then signal_candidates.residuals.list for the dominant blocker bucket.",
        "Inspect 1-3 representative cases with signal_candidates.explain before proposing any write.",
        "Read the affected system_interests.read result and system_interests.compile_status.list so candidateSignals, profile policy, and compile errors are visible.",
        "Call operator.tuning.recommend before changing interests, templates, policies, or sources.",
      ],
      recommendedTools: {
        read: [
          "admin.summary.get",
          "signal_candidates.residuals.summary",
          "signal_candidates.residuals.list",
          "signal_candidates.explain",
          "system_interests.read",
          "system_interests.compile_status.list",
          "llm_budget.summary",
          "operator.system.health",
          "operator.issue.explain",
          "operator.tuning.recommend",
          "maintenance.reindex_jobs.list",
          "operator.effect.verify",
          "operator.report.verify",
        ],
        boundedWrites: [
          "system_interests.update",
          "llm_templates.update",
          "content_filter_policies.update",
          "content_analysis_policies.update",
          "channels.update",
          "discovery.policies.activate",
          "maintenance.reindex.request",
        ],
      },
      diagnosticBranches: [
        {
          branch: "acquisition_gap",
          evidence:
            "No or too few signal_candidates exist for the expected source family; source inventory, query attempts, probes, or channels show missing acquisition.",
          response:
            "Repair Discovery/source coverage through discovery and channel tools. Do not loosen selection until acquisition evidence exists.",
        },
        {
          branch: "channel_or_fetch_failure",
          evidence:
            "channels.read/list, fetch_runs.list, web_resources.list, or channels.bottlenecks.* show transport/provider-shape failures.",
          response:
            "Treat RSS/channel volume as acquisition evidence only. Fix provider config, polling, alternatives, or adapter backlog before judging selection.",
        },
        {
          branch: "high_filter_rows_low_distinct_candidates",
          evidence:
            "operator.selection.dashboard shows large filterRows for a reason but much smaller distinctCandidateCount because candidates are evaluated across many criteria.",
          response:
            "Do not multiply row counts into candidate impact. Inspect 10-30 representative rejected candidates, identify false-negative patterns, then repair only the specific config/heuristic proven by samples.",
        },
        {
          branch: "semantic_rejected/no_system_match",
          evidence:
            "Representative signal_candidates.explain rows show no matching system criterion or semantic rejection before gray-zone/LLM review.",
          response:
            "First classify signalVisibility. For hidden_intent or unknown, keep must_have_terms=[] and short_tokens_required=[]; use candidateSignals-first recovery with literal observable cue fragments, signal families, source/context evidence, near-miss negatives, and bounded replay. llmReviewMode=always does not bypass semantic rejection.",
        },
        {
          branch: "gray_zone_or_hold",
          evidence:
            "Residuals or holds show gray_zone_hold, candidate_signal_hold, buyer_intent_hold, project_intent_hold, or llm_review_pending.",
          response:
            "Inspect holds summary/list/explain, then replay only bounded docIds chunks. Prefer 25 items and never more than 50 when LLM reviews may run.",
        },
        {
          branch: "llm_review_diagnostic",
          evidence: "LLM spend is zero or unexpectedly low.",
          response:
            "Classify llm_review_disabled, budget_exhausted, no_pending_gray_zone, worker_not_running, provider_credentials_missing, or semantic rejection before LLM. 0 LLM spend is not proof the LLM path is broken.",
        },
        {
          branch: "discovery_runtime_credentials_missing",
          evidence:
            "Live Discovery returns runtime_credentials_missing or provider readiness errors.",
          response:
            "Treat this as preflight/not_applicable for live-provider proof. Do not tune maxRunCostCents or broaden sources to fix absent credentials.",
        },
      ],
      sessionFlow: [
        "Classify the failure layer before mutations: acquisition gap, channel/fetch failure, semantic_rejected/no_system_match, gray-zone/hold, LLM review issue, or Discovery runtime credentials missing.",
        "Classify signalVisibility before hard gates: explicit_marker, hidden_intent, mixed, or unknown.",
        "For hidden_intent or unknown, empty hard gates are baseline. Do not add must_have_terms or short_tokens_required as first repair.",
        "For mixed signals, split lane-like config first: explicit marker lane, hidden intent lane, source context lane, and negative-control lane as needed.",
        "Check operator.selection.dashboard staleProfileDiagnostics before trusting residual counters or gray-zone collapse.",
        "For 0 selected with existing signal_candidates, inspect residuals and filterReasonBreakdown before adding sources. More RSS may increase acquisition volume without proving selected-signal recall.",
        "For semantic_rejected/no_system_match, read one affected interest and compile status, then compare representative candidate evidence with the interest's signal families and candidateSignals.",
        "If the interest is a keyword pile or only short positive_texts, rewrite it into signal families, real positive prototypes, near-miss negatives, candidate positive cue groups, and candidate negative cue groups. For hidden/operational signals, do not recommend adding positive terms as the main repair.",
        "For candidateSignals, group.name is a conceptual label and group.cues are literal observable fragments; replace snake_case/id-like cue labels with text seen in representative candidates.",
        "Treat backfill criteriaMatches/interestMatches and filterReasonCounts as processed-row counters, not distinct candidates and not selected-signal proof.",
        "If gray_zone collapses, classify stale replay, hard-filter collapse, residual distribution, rejected samples, selected quality, and hold quality before calling it precision improvement.",
        "Apply at most one bounded write. Do not mass edit 30 interests, mass-set strictness=broad, or rewrite LLM templates before a representative candidate proves the needed change.",
        "For wrapper_directory_noise, time_window, must_not, content_kind and other hard filters, never recommend global disable from row counts alone; sample first and replay explicit docIds.",
        "Read the changed entity back through MCP. If the read-back does not show the intended policy/template/interest fields, stop and fix the write path.",
        "Use only canonical system-interest write fields: candidate_positive_signals, candidate_negative_signals, selection_profile_llm_review_mode, and allowed_content_kinds.",
        "Replay only explicit docIds from the inspected residual bucket. Use maintenance.reindex.request with bounded payload.options.docIds chunks and a reason tied to the calibration.",
        "After replay, use maintenance.reindex_jobs.list, operator.effect.verify, and operator.report.verify reportKind=selection or selection_tuning before the next change.",
      ],
      antiPatterns: [
        "Starting 0 selected diagnosis with mass strictness=broad.",
        "Editing many interests or LLM templates without 1-3 representative signal_candidates.explain rows.",
        "Treating 0 LLM spend as an LLM outage before checking no_pending_gray_zone or semantic rejection before LLM.",
        "Using only short keyword phrases in positive_texts instead of representative positive prototypes.",
        "Recommending positive-term expansion for hidden operational signals before candidateSignals, policy evidence, and near-miss negatives.",
        "Reporting gray-zone collapse as more precise without selected and near-miss sample proof.",
        "Treating criteriaMatches/interestMatches as selected-signal proof.",
        "Treating filterReasonCounts as unique candidate counts.",
        "Globally removing wrapper/source-navigation filters without representative false-negative samples.",
        "Using stale report channel counts or historical/transient fetch failures as current source health.",
        "Treating broad strictness as a fix for missing item-level evidence.",
        "Using OR must_have_terms as if it were hidden-signal safe.",
        "Using short_tokens_required as a replacement OR keyword list.",
        "Using candidateSignals cues that are concept labels rather than literal text fragments.",
        "Adding more RSS/channel rows as selection proof.",
        "Masking API/portal/search sources as RSS/website instead of adapter_required or api_mapping_required.",
        "Using discovery.brief.preview as a workaround for domain_contamination or persisted DiscoveryBrief validation.",
        "Reporting intended system-interest profile/candidateSignals writes before readBackVerification proves persisted state.",
        "Skipping MCP read-back and bounded replay proof after a write.",
      ],
      invariants: [
        "llmReviewMode=always is not a bypass for semantic_rejected/no_system_match.",
        "candidateSignals can recover items into gray/hold/review paths; they select only when an explicit auto-select policy permits it and clean evidence thresholds/veto checks pass.",
        "Domain examples are calibration evidence only; product behavior must be changed through admin/MCP configuration and read-back.",
        "Live Discovery without runtime credentials is preflight/not_applicable, not a budget-tuning task.",
      ],
      verifyAfterWrite: [
        "Read the changed system interest, LLM template, content policy, channel, or Discovery policy back through MCP.",
        "Replay only bounded docIds from the diagnosed residual bucket.",
        "Verify replay completion through maintenance.reindex_jobs.list.",
        "Call operator.report.verify with reportKind=selection_tuning or selection, and includeSamples=true when reporting calibration success.",
      ],
    }),
  },
];
