import type { McpResourceDefinition } from "./types";
import { calibrationScenarioResources } from "./scenarios-calibration";

export const scenarioResources: readonly McpResourceDefinition[] = [
  {
    uri: "signalops://guide/scenarios/sequences",
    name: "guide.scenarios.sequences",
    description: "Concrete MCP playbook for sequence drafting, execution, recovery, and archive decisions.",
    mimeType: "application/json",
    read: async () => ({
      objective:
        "Use this scenario when the job is to create, update, run, inspect, retry, cancel, or archive automation sequences through the SignalOps control plane.",
      startWith: [
        "Read signalops://admin/summary and signalops://sequences first.",
        "If the sequence does not exist yet, draft it with prompt sequence.draft before calling write tools.",
        "Prefer one sequence at a time; do not bundle unrelated automation changes into one session.",
      ],
      recommendedTools: {
        read: [
          "sequences.list",
          "sequences.read",
          "sequences.runs.read",
          "sequences.run_task_runs.list",
          "maintenance.reindex_jobs.list",
        ],
        write: [
          "maintenance.reindex.request",
          "sequences.create",
          "sequences.update",
          "sequences.run",
          "sequences.cancel_run",
          "sequences.retry_run",
          "sequences.archive",
        ],
      },
      intentRouting: [
        {
          phrases: [
            "старые статьи",
            "old signal_candidates",
            "historical signal_candidates",
            "existing content",
            "прогнать заново",
            "перепроверить по интересам",
            "selected шумит",
            "pass_through noise",
            "after Example C/templates/criteria changes",
          ],
          tool: "maintenance.reindex.request",
          payload: {
            indexName: "interest_centroids",
            jobKind: "backfill",
          },
          reason:
            "Selection replay recomputes current system-interest criteria evidence, interest_filter_results, and final_selection_results for existing content.",
        },
        {
          phrases: ["centroid index", "vector index", "only rebuild index", "только обновить индекс"],
          tool: "maintenance.reindex.request",
          payload: {
            indexName: "interest_centroids",
            jobKind: "rebuild",
          },
          reason: "Rebuild refreshes derived centroid/vector indexes and is not a historical selection replay.",
        },
        {
          phrases: ["NER", "entities", "sentiment", "category", "content labels", "filter evidence"],
          tool: "content_analysis.backfill.request",
          reason:
            "Content analysis backfill refreshes analysis/label/filter evidence only; it is not a replacement for selection replay.",
        },
      ],
      sessionFlow: [
        "Read the current sequence definition and recent runs before changing anything.",
        "Draft or review the task graph with sequence.draft when the intended workflow is non-trivial.",
        "For Default Reindex or other reindex maintenance work, use maintenance.reindex.request; do not manually call sequences.run unless you already have a valid reindex_job/event context.",
        "Do not use content_analysis.backfill.request as a substitute for selection replay; it does not recompute signal_candidate.match_criteria, interest_filter_results, or final_selection_results.",
        "Create or update the sequence, then run it in a bounded way and poll run state before deciding next actions.",
        "If a run fails, inspect the failed run details before retrying; treat retry as a recovery action, not a blind rerun.",
      ],
      destructiveCautions: [
        "Archive only after the run evidence and owning intent are clear.",
        "Cancel only active runs that should stop now; do not use cancel as a substitute for diagnosis.",
      ],
      verifyAfterWrite: [
        "Read the updated sequence back through sequences.read.",
        "Read the run state after run/cancel/retry and confirm the resulting status.",
      ],
    }),
  },
  {
    uri: "signalops://guide/scenarios/discovery",
    name: "guide.scenarios.discovery",
    description: "Concrete MCP playbook for Discovery vNext artifacts, inventory, policy, replay, and rollback.",
    mimeType: "application/json",
    read: async () => ({
      objective:
        "Use this scenario for vNext source discovery through typed artifacts, candidate acquisition, probing, source understanding, deterministic routing, source inventory, replay, and rollback.",
      startWith: [
        "Read signalops://discovery/runs, signalops://discovery/artifacts, signalops://discovery/candidates, signalops://discovery/source-inventory, and signalops://discovery/policies first.",
        "Create a Discovery vNext run before persisting artifacts or candidates.",
        "Use prompts discovery.artifact.review, discovery.source_understanding.review, and discovery.yield.review when artifact quality, policy fit, or routing evidence is unclear.",
      ],
      recommendedTools: {
        read: [
          "discovery.runs.list",
          "discovery.artifacts.list",
          "discovery.candidates.list",
          "discovery.source_inventory.list",
          "discovery.policies.list",
          "discovery.adapter_backlog.list",
          "discovery.feedback.list",
          "discovery.replay_runs.list",
          "discovery.rollback_groups.list",
          "discovery.eval_runs.list",
        ],
        write: [
          "discovery.runs.create",
          "discovery.runs.cancel",
          "discovery.brief.preview",
          "discovery.artifacts.create",
          "discovery.mega_loop.preview",
          "discovery.candidates.create",
          "discovery.probe.execute",
          "discovery.understand.preview",
          "discovery.route.preview",
          "discovery.routing.apply",
          "discovery.probation.handoff",
          "discovery.policies.activate",
          "discovery.replay.start",
          "discovery.rollback.prepare",
          "discovery.rollback.apply",
          "discovery.feedback.submit",
        ],
      },
      sessionFlow: [
        "Compile a DiscoveryBrief with domain-neutral constraints and persist only valid artifacts.",
        "Run bounded mega-loop/candidate acquisition; preserve rediscovery counts and query quality artifacts.",
        "Probe through fetchers-owned static/feed/sitemap semantics; browser probing requires explicit active probe policy.",
        "Build SourceUnderstanding from probe evidence and candidate facts, then route with the active routing policy.",
        "Historical yield is telemetry only; never use it as a keep/drop reason.",
        "Adapter needs go to adapter_backlog; accepted probation handoff must use source_channels and source channel sync outbox discipline.",
        "Use replay before changing policy and prepare rollback groups before destructive rollback.",
      ],
      destructiveCautions: [
        "Destructive rollback requires write.destructive scope and confirm=true.",
        "Do not delete shared source_channels, source_channel_runtime_state, outbox, fetcher-owned content/fetch tables, web_resources, or downstream filtering state as Discovery cleanup.",
      ],
      verifyAfterWrite: [
        "Read back the updated run, artifact, candidate, source inventory record, policy, replay run, rollback group, or feedback event after every mutation.",
        "After discovery.runs.create, treat the result as queued until a worker or replay result updates it.",
        "After probation handoff, confirm the resulting source_channel and source.channel.sync.requested outbox event.",
        "Before the final discovery report, read discovery.runs.list, discovery.artifacts.list, discovery.source_inventory.list, and discovery.policies.list.",
      ],
    }),
  },
  {
    uri: "signalops://guide/scenarios/discovery-live-gap-hunting",
    name: "guide.scenarios.discovery-live-gap-hunting",
    description: "MCP-only live Discovery vNext gap-hunting playbook for domain-neutral operator proofs.",
    mimeType: "application/json",
    read: async () => ({
      objective:
        "Use this scenario to prove and debug the real Discovery vNext operator flow through MCP only, across multiple domain-neutral signal families.",
      startWith: [
        "Use MCP initialize, tools/list, resources/list and prompts/list to prove the client can see the needed surfaces.",
        "Read discovery, funnel-calibration and operating-model guides before writes.",
        "Run operator.funnel.audit, operator.funnel.autoplan, operator.funnel.iteration.recommend and discovery.source_families.coverage before creating live interests.",
      ],
      scenarioPacks: [
        "public_procurement",
        "security_advisories",
        "policy_regulatory",
        "research_grants",
        "software_changelogs",
      ],
      requiredMcpSurfaces: [
        "system_interests.create/read/list/compile_status.list",
        "llm_templates.list/read/create/update",
        "discovery.runs.execute/read/list",
        "discovery.run_steps.list",
        "discovery.query_attempts.list",
        "discovery.artifacts.list/read",
        "discovery.candidates.list/read",
        "discovery.probe.plan_preview",
        "discovery.probe.execute",
        "discovery.understand.preview",
        "discovery.routing.apply",
        "discovery.probation.handoff",
        "discovery.replay.start",
        "discovery.feedback.submit",
        "operator.report.verify",
      ],
      gapClasses: [
        "missing_mcp_surface",
        "schema_gap",
        "runtime_gap",
        "diagnostic_gap",
        "policy_gap",
        "provider_gap",
      ],
      successCriteria: [
        "Every product mutation uses MCP and is followed by an MCP read-back.",
        "At least three scenario packs produce candidates or explainable live provider failures.",
        "Query attempts include live provider metadata.",
        "Persisted artifacts, candidates, inventory, monitoring state, observations or adapter backlog are visible through MCP diagnostics.",
      ],
      evidencePolicy:
        "Live evidence is retained by default for manual inspection. Cleanup must be explicit and separate from the proof.",
    }),
  },
  ...calibrationScenarioResources,
  {
    uri: "signalops://guide/scenarios/system-interests",
    name: "guide.scenarios.system-interests",
    description: "Concrete MCP playbook for creating, refining, archiving, and deleting system interests.",
    mimeType: "application/json",
    read: async () => ({
      objective:
        "Use this scenario for editorial/operator interest maintenance when SignalOps needs a bounded monitoring intent for a topic, audience, or signal family.",
      startWith: [
        "Read signalops://system-interests first to avoid duplicating an existing interest.",
        "Use prompt system_interest.create to draft the initial payload when the topic needs careful inclusion/exclusion framing.",
        "For 0 selected or semantic_rejected/no_system_match, read signalops://guide/scenarios/selection-calibration before changing the interest.",
        "For hidden, mixed, rare or unknown signals, read signalops://guide/reference/hidden-signal-evidence-lanes before adding hard gates.",
      ],
      recommendedTools: {
        read: ["system_interests.list", "system_interests.read"],
        write: [
          "system_interests.create",
          "system_interests.update",
          "system_interests.archive",
          "system_interests.delete",
        ],
      },
      sessionFlow: [
        "Read nearby interests and confirm the new topic is genuinely distinct.",
        "If the interest is part of a calibrated funnel, compare it with the reference signal family before creating another broad or overlapping interest.",
        "Draft signal families, representative positive prototypes, near-miss negative prototypes, candidate positive/negative cue groups, allowed content kinds and scope before creating the interest.",
        "Avoid short keyword piles in positive_texts; each positive prototype should describe item-level evidence that would justify a match.",
        "For candidateSignals, group cues by evidence role, such as buyer ask, project object, deliverable/scope, budget/timeline, source authority, and near-miss negative patterns.",
        "For candidateSignals, group.name is the conceptual label; group.cues must be literal observable text fragments that can appear in candidate title/lead/body.",
        "For hidden/unknown signals, keep must_have_terms=[] and short_tokens_required=[] as the baseline. For explicit marker lanes, add hard gates only after mandatory-marker proof and bounded replay.",
        "For mixed signals, split lane-like interests/criteria/config-pack entries so hidden lanes do not inherit explicit-marker gates.",
        "For rare-signal funnels, prefer negative cues and LLM review over broad must-have gates unless a marker is truly mandatory.",
        "Use newline-separated strings or string arrays for list-like fields. For allowed_content_kinds, use concrete entries such as editorial, listing, and document, not one combined text value.",
        "If a write tool returns an MCP error, stop and correct the payload; do not report creation until system_interests.read or list proves the new entity exists.",
        "Update only one interest at a time so resulting monitoring behavior remains explainable.",
      ],
      destructiveCautions: [
        "Archive before delete when the operator may need a recoverable historical trail.",
        "Delete only with explicit confirmation and only when the interest is clearly obsolete or erroneous.",
      ],
      verifyAfterWrite: [
        "Read the interest back through system_interests.read.",
        "Check system_interests.compile_status.list when candidateSignals, profile policy, or template-linked fields changed.",
        "Re-read the interests list to confirm the intended lifecycle state.",
      ],
    }),
  },
  {
    uri: "signalops://guide/scenarios/llm-templates",
    name: "guide.scenarios.llm-templates",
    description: "Concrete MCP playbook for LLM template drafting, bounded edits, archive, and delete decisions.",
    mimeType: "application/json",
    read: async () => ({
      objective:
        "Use this scenario for operator-owned LLM template maintenance, especially when tuning prompt text, model settings, or template lifecycle state.",
      startWith: [
        "Read signalops://templates/llm first and inspect the current template before editing.",
        "Keep changes bounded to one template and one intent change per session whenever possible.",
      ],
      recommendedTools: {
        read: ["llm_templates.list", "llm_templates.read"],
        write: [
          "llm_templates.create",
          "llm_templates.update",
          "llm_templates.archive",
          "llm_templates.delete",
        ],
      },
      sessionFlow: [
        "Read the current template body and metadata first.",
        "State the exact behavior change being sought before editing prompt text or configuration.",
        "Prefer incremental edits over wholesale rewrites unless the template is clearly being replaced.",
      ],
      destructiveCautions: [
        "Archive before delete when you may need to preserve lineage or compare prompt behavior later.",
        "Do not widen template authority or implied scope silently; document why the template changed.",
      ],
      verifyAfterWrite: [
        "Read the updated template back through llm_templates.read.",
        "Confirm list visibility or lifecycle status through signalops://templates/llm.",
      ],
    }),
  },
  {
    uri: "signalops://guide/scenarios/channels",
    name: "guide.scenarios.channels",
    description: "Concrete MCP playbook for channel creation, tuning, verification, and removal.",
    mimeType: "application/json",
    read: async () => ({
      objective:
        "Use this scenario for source-channel onboarding and maintenance, including Discovery vNext probation handoff follow-up, metadata correction, and bounded cleanup.",
      startWith: [
        "Read signalops://channels first to check whether the source already exists or overlaps with an existing channel.",
        "When a channel comes from Discovery vNext probation handoff, preserve SourceUnderstanding, RoutingDecision, source inventory, and outbox evidence before making manual edits.",
      ],
      recommendedTools: {
        read: [
          "channels.list",
          "channels.read",
          "channels.bulk_onboard.plan",
          "channels.alternatives.plan",
          "channels.bulk_onboard.verify",
          "fetch_runs.list",
          "web_resources.list",
        ],
        write: [
          "channels.create",
          "channels.update",
          "channels.bulk_onboard.apply",
          "channels.alternatives.start",
          "channels.delete",
        ],
      },
      sessionFlow: [
        "Read existing channels and identify whether this is a new source, a correction, or a cleanup action.",
        "For more than one explicit source, use channels.bulk_onboard.plan first; inspect create/update/duplicate/invalid/mismatch/override rows before applying.",
        "For RSS rows that look like website roots/pages or structurally failing channels, run channels.bottlenecks.summary/list and channels.alternatives.plan; valid RSS candidates must come from feed-probe evidence or a feed-like URL.",
        "When RSS fails with auth_or_blocked_403, not_acceptable_406, malformed_feed, html_instead_of_feed, gone_404, or equivalent error text, review channels.alternatives.plan website_fallback candidates. They are needs_probe candidates only, not auto-created channels.",
        "If a website_fallback candidate is safe, run channels.bulk_onboard.plan with providerType=website, then channels.bulk_onboard.apply, then channels.bulk_onboard.verify. Do not create a website channel blindly from an invalid RSS URL.",
        "Apply only the current planFingerprint. Use confirm=true for updates and overrideReason only when source evidence justifies a provider mismatch override.",
        "For promoted sources, compare promoted metadata with the source evidence before broadening tags or trust.",
        "Apply bounded edits, then verify the resulting channel state and any downstream list visibility.",
        "For website channels, verify acquisition through fetch_runs.list and web_resources.list before judging signal_candidate/selection outcomes.",
      ],
      destructiveCautions: [
        "Delete only with explicit confirmation and only when the channel is invalid, duplicate, or intentionally removed.",
      ],
      verifyAfterWrite: [
        "Read the channel back through channels.read.",
        "For website channels, inspect web_resources with projection=all, then compare projection=resource_only and projection=projected.",
        "Do not treat projected-but-rejected rows as channel creation failure; that is downstream selection/filtering evidence.",
        "Re-read signalops://channels to confirm the catalog reflects the intended change.",
      ],
    }),
  },
  {
    uri: "signalops://guide/scenarios/signal_candidate-diagnostics",
    name: "guide.scenarios.signal_candidate-diagnostics",
    description: "Concrete MCP playbook for signal_candidate residual analysis and evidence-based tuning.",
    mimeType: "application/json",
    read: async () => ({
      objective:
        "Use this scenario to understand why editorial observations did not reach selected content and to produce bounded tuning recommendations from signal_candidate/content evidence.",
      startWith: [
        "Read signalops://signal-candidates/residuals-summary first to identify the dominant blocker buckets.",
        "Use signal_candidates.residuals.list to inspect representative rows for one blocker at a time.",
        "Inspect the same case through signal_candidates.explain and, when relevant, content_items.explain to compare editorial observation truth with selected/public truth.",
      ],
      recommendedTools: {
        read: [
          "signal_candidates.list",
          "signal_candidates.read",
          "signal_candidates.explain",
          "signal_candidates.residuals.list",
          "signal_candidates.residuals.summary",
          "signal_candidates.holds.summary",
          "signal_candidates.holds.list",
          "signal_candidates.holds.explain",
          "content_items.list",
          "content_items.read",
          "content_items.explain",
          "operator.selection.precision_audit",
          "operator.tuning.recommend",
          "maintenance.reindex_jobs.list",
          "operator.report.verify",
          "operator.effect.verify",
        ],
      writeFollowThrough: [
        "maintenance.reindex.request",
        "system_interests.update",
        "llm_templates.update",
        "discovery.artifacts.create",
        "discovery.policies.activate",
        ],
      },
      sessionFlow: [
        "Diagnose residual buckets before drilling into single examples.",
        "Separate technical filtering, semantic rejection, gray-zone hold, and review-pending cases before proposing config changes.",
        "For semantic_rejected/no_system_match, do not begin with broad strictness, LLM template rewrites, positive-term expansion, or more RSS volume. Inspect the candidate explanation, the affected system interest, compile status, and candidateSignals, then tune one interest from repeated evidence.",
        "For hidden/operational signals, use candidateSignals, policy evidence, and near-miss negatives before changing positive_texts; positive_texts should remain representative prototypes, not keyword recovery.",
        "Treat criteriaMatches/interestMatches as backfill processor counters. Use final_selection_results, content_items, residual samples, and operator.report.verify for selected-signal proof.",
        "Do not infer improvement from gray_zone collapse alone; inspect rejected samples, hold quality, replay freshness, and selected/near-miss samples.",
        "If selected count is 0, run signalops://guide/scenarios/selection-calibration before any mass write.",
        "For gray_zone_hold/candidate_signal_hold, call operator.tuning.recommend with domain=selection, objective=increase_recall, residualBucket=gray_zone_hold, then inspect signal_candidates.holds.summary/list/explain before replay.",
        "If LLM spend is 0, classify llm_review_disabled, budget_exhausted, no_pending_gray_zone, worker_not_running, provider_credentials_missing, or semantic rejection before LLM before changing budgets or templates.",
        "When selected content itself is noisy, call operator.selection.precision_audit, then tune negative/veto cues or candidateSignals through MCP/admin and replay only the weak selected docIds in bounded chunks.",
        "Treat context candidate signals as diagnostics. Replay buyer_intent/project_intent holds first, in chunks of 25 by default and never more than 50 when LLM reviews may run.",
        "After a bounded replay chunk, wait for maintenance.reindex_jobs.list to show completed or failed, then run operator.report.verify reportKind=selection, operator.report.verify reportKind=selection_hold_quality, and operator.effect.verify before the next chunk or any interest/template edit.",
        "Tune one interest, template, or discovery target policy at a time and keep recommendations bounded to repeated evidence patterns.",
        "After any mutation outside this read-first flow, re-read the affected entity through MCP before making the next recommendation.",
      ],
      invariants: [
        "Downstream signal_candidate/content diagnostics may inform operator prompts and decisions, but they must not become direct discovery auto-approval inputs.",
        "Do not treat one residual row as enough evidence for broad policy changes; look for repeated patterns inside the same bucket.",
        "A bounded replay chunk is a recalculation step, not proof of improved quality. Report impact only from operator.report.verify and operator.effect.verify read-back.",
        "There is no separate public selected gate: final_selection_results selected rows are what web should show. Fix noisy selected rows at the selection pipeline/config layer.",
        "Source priors, channel health, and source bottlenecks can explain acquisition or repair, but they must not select, rank, escalate, or publish signal_candidate/content items.",
        "llmReviewMode=always does not bypass semantic_rejected/no_system_match.",
      ],
    }),
  },
  {
    uri: "signalops://guide/scenarios/observability",
    name: "guide.scenarios.observability",
    description: "Concrete MCP playbook for read-only operator diagnosis across admin summary, budgets, web resources, and fetch runs.",
    mimeType: "application/json",
    read: async () => ({
      objective:
        "Use this scenario for read-only operator diagnosis when the goal is to understand current system state, recent runtime behavior, or bounded evidence before deciding whether a write is needed.",
      startWith: [
        "Read signalops://admin/summary first.",
        "Pull only the relevant read surfaces for the suspected issue domain: sequences, discovery summary, web resources, fetch runs, or LLM budget.",
      ],
      recommendedTools: {
        read: [
          "admin.summary.get",
          "llm_budget.summary",
          "web_resources.list",
          "web_resources.read",
          "fetch_runs.list",
          "sequences.list",
          "sequence_runs.list",
          "discovery.summary.get",
        ],
      },
      sessionFlow: [
        "Start broad with summary surfaces, then narrow to the affected entity or run.",
        "Prefer evidence collection first; only move into writes after the cause and desired change are clear.",
        "Use this scenario to prepare a human/operator explanation when the system is healthy but yield or usefulness is weak.",
      ],
      destructiveCautions: [
        "Observability work is read-only by default; switching into writes should be an explicit decision, not an accidental next step.",
      ],
      verifyAfterWrite: [
        "If the session escalates into a write, re-enter the relevant domain-specific scenario and verify there.",
      ],
    }),
  },
  {
    uri: "signalops://guide/scenarios/cleanup",
    name: "guide.scenarios.cleanup",
    description: "Concrete MCP playbook for safe cleanup after experiments, tests, and bounded operator changes.",
    mimeType: "application/json",
    read: async () => ({
      objective:
        "Use this scenario when a session created temporary sequences, channels, interests, templates, missions, or tokens that now need orderly cleanup without losing audit truth.",
      startWith: [
        "Read the affected entities first and decide which artifacts should remain for audit or acceptance evidence.",
        "Use admin.mcp_tokens.list/revoke/delete_revoked for MCP token inventory and lifecycle; do not call admin REST directly and do not guess raw database column names.",
        "Treat sequences with created_by starting migration: as protected system objects; do not archive them during cleanup.",
        "Use prompt cleanup.guidance when the cleanup spans more than one entity or mixes reversible and destructive actions.",
      ],
      recommendedTools: {
        read: [
          "admin.summary.get",
          "admin.mcp_tokens.list",
          "admin.mcp_tokens.revoke",
          "admin.mcp_tokens.delete_revoked",
          "sequences.read",
          "channels.read",
          "system_interests.read",
          "llm_templates.read",
          "discovery.artifacts.read",
          "discovery.source_inventory.read",
        ],
        write: [
          "sequences.archive",
          "system_interests.archive",
          "system_interests.delete",
          "llm_templates.archive",
          "llm_templates.delete",
          "channels.delete",
        ],
      },
      sessionFlow: [
        "Separate reversible cleanup from irreversible cleanup before calling any destructive tools.",
        "Prefer archive when the entity may still be useful as evidence, lineage, or rollback context.",
        "Archive only test/operator-created sequences; leave Default, Adaptive Discovery, Website Resource Extract, and other migration-owned sequences unchanged.",
        "Use delete only for clearly erroneous or intentionally disposable artifacts, and only with explicit confirmation.",
      ],
      destructiveCautions: [
        "Do not delete audit-relevant artifacts just to make the workspace look tidy.",
        "Re-confirm identifiers before destructive actions so cleanup does not hit the wrong entity.",
      ],
      verifyAfterWrite: [
        "Read the affected entities back and confirm the final lifecycle state matches the cleanup plan.",
      ],
      tokenInventoryNotes: {
        tool: "admin.mcp_tokens.list",
        databaseColumns: [
          "token_id",
          "label",
          "token_prefix",
          "scopes",
          "status",
          "issued_by_user_id",
          "revoked_by_user_id",
          "revoked_at",
          "expires_at",
          "last_used_at",
          "last_used_ip",
          "last_used_user_agent",
          "created_at",
          "updated_at",
        ],
        warning:
          "Raw SQL against mcp_access_tokens is not needed for normal MCP cleanup. If direct SQL is used during debugging, use these canonical column names; there are no id/name/is_active/is_revoked columns.",
      },
    }),
  },
];
