from __future__ import annotations

import re

TITLECASE_PATTERN = re.compile(
    r"\b[A-ZА-ЯІЇЄҐ][a-zа-яіїєґ'’-]+(?:\s+[A-ZА-ЯІЇЄҐ][a-zа-яіїєґ'’-]+){0,3}\b"
)
DATE_PATTERN = re.compile(r"\b(?:20\d{2}|19\d{2})[-/.](?:0?[1-9]|1[0-2])[-/.](?:0?[1-9]|[12]\d|3[01])\b")
ORG_HINT_PATTERN = re.compile(
    r"\b(?:inc|llc|ltd|corp|corporation|company|group|university|foundation|gmbh|s\.a\.|plc)\b",
    re.IGNORECASE,
)
GPE_HINTS = {
    "United States",
    "United Kingdom",
    "European Union",
    "Poland",
    "Germany",
    "France",
    "Ukraine",
    "Warsaw",
    "London",
    "Berlin",
    "Paris",
    "Kyiv",
    "New York",
}
POSITIVE_TERMS = {
    "approve",
    "approved",
    "benefit",
    "boost",
    "breakthrough",
    "growth",
    "improve",
    "improved",
    "positive",
    "profit",
    "record",
    "success",
    "surge",
    "win",
    "выиграл",
    "одобрил",
    "победа",
    "позитив",
    "прибыль",
    "рост",
    "улучшение",
    "успех",
}
NEGATIVE_TERMS = {
    "attack",
    "ban",
    "bankruptcy",
    "collapse",
    "concern",
    "crisis",
    "damage",
    "decline",
    "fail",
    "failed",
    "fraud",
    "loss",
    "negative",
    "risk",
    "scandal",
    "strike",
    "war",
    "банкротство",
    "война",
    "запрет",
    "кризис",
    "негатив",
    "падение",
    "потери",
    "риск",
    "скандал",
    "ущерб",
}
RISK_TERMS = {
    "attack",
    "breach",
    "collapse",
    "crisis",
    "fraud",
    "investigation",
    "lawsuit",
    "risk",
    "sanction",
    "war",
    "атака",
    "война",
    "иск",
    "кризис",
    "расследование",
    "риск",
    "санкции",
}
CATEGORY_TERMS = {
    "business": {
        "acquisition",
        "bank",
        "company",
        "earnings",
        "market",
        "merger",
        "profit",
        "revenue",
        "stock",
        "банк",
        "бизнес",
        "выручка",
        "компания",
        "прибыль",
        "рынок",
    },
    "technology": {
        "ai",
        "algorithm",
        "chip",
        "cloud",
        "cyber",
        "data",
        "software",
        "technology",
        "алгоритм",
        "данные",
        "кибер",
        "облако",
        "технологии",
        "чип",
    },
    "politics": {
        "cabinet",
        "campaign",
        "election",
        "government",
        "minister",
        "parliament",
        "policy",
        "president",
        "выборы",
        "кабинет",
        "министр",
        "парламент",
        "политика",
        "правительство",
        "президент",
    },
    "security": {
        "attack",
        "defense",
        "military",
        "sanction",
        "security",
        "war",
        "атака",
        "безопасность",
        "война",
        "оборона",
        "санкции",
    },
    "health": {
        "doctor",
        "drug",
        "health",
        "hospital",
        "medical",
        "patient",
        "vaccine",
        "вакцина",
        "врач",
        "здоровье",
        "медицина",
        "пациент",
    },
    "climate": {
        "climate",
        "emissions",
        "energy",
        "environment",
        "flood",
        "renewable",
        "weather",
        "выбросы",
        "климат",
        "погода",
        "энергия",
    },
    "science": {
        "discovery",
        "experiment",
        "research",
        "science",
        "space",
        "study",
        "исследование",
        "космос",
        "наука",
        "эксперимент",
    },
    "sports": {
        "championship",
        "coach",
        "football",
        "game",
        "match",
        "team",
        "tournament",
        "игра",
        "матч",
        "спорт",
        "турнир",
        "футбол",
    },
    "culture": {
        "artist",
        "book",
        "culture",
        "film",
        "music",
        "museum",
        "театр",
        "культура",
        "музыка",
        "фильм",
    },
    "legal": {
        "court",
        "judge",
        "law",
        "lawsuit",
        "legal",
        "regulation",
        "суд",
        "закон",
        "иск",
        "регулятор",
    },
}
WORD_PATTERN = re.compile(r"[0-9A-Za-zА-Яа-яІіЇїЄєҐґ'’-]+")
URL_PATTERN = re.compile(r"https?://[^\s)>\"]+", re.IGNORECASE)
MONEY_PATTERN = re.compile(
    r"(?:[$€£]\s?\d[\d,]*(?:\.\d+)?(?:\s?[kKmM])?|\d[\d,]*(?:\.\d+)?\s?(?:USD|EUR|GBP|PLN|грн|UAH))"
)
JOB_CUE_TERMS = {
    "career",
    "developer",
    "engineer",
    "full-time",
    "hiring",
    "job",
    "onsite",
    "remote",
    "salary",
    "vacancy",
}
BUYER_CUE_TERMS = {
    "bid",
    "contract",
    "deadline",
    "implementation",
    "migration",
    "outsourcing",
    "procurement",
    "proposal",
    "rfp",
    "tender",
}

