from __future__ import annotations

from fastapi import HTTPException

from services.api.app.content_selection.payloads import (
    build_candidate_signal_quality_warnings,
    build_content_kind_selection_explain_payload,
    build_fallback_selection_blocker_payload,
    build_hard_gate_safety_warnings,
    build_interest_filter_count_summary,
    build_resource_selection_explain_payload,
    build_selection_diagnostics_payload,
    build_selection_diagnostics_payload_from_counts,
    build_selection_explain_payload,
    build_selection_guidance_payload,
    normalize_system_interest_selection_profile_payload,
)
from services.api.app.content_selection.projection import (
    apply_resource_selection_payload,
    apply_signal_candidate_selection_payload,
    build_content_item_id,
    build_editorial_content_item_preview_from_signal_candidate,
    get_selected_content_item_preview,
    parse_content_item_id,
    query_count,
)
from services.api.app.content_selection.sql_fragments import (
    canonical_signal_candidate_family_expr,
    canonical_signal_candidate_family_order_clause,
    combined_content_items_select_sql,
    editorial_content_select_sql,
    effective_system_selected_expr,
    effective_system_selection_decision_expr,
    feed_eligible_signal_candidate_clause,
    final_selection_join_clause,
    primary_media_join_clause,
    processed_signal_candidate_clause,
    resource_content_select_sql,
    signal_candidate_observation_join_clause,
    signal_candidate_preview_projection,
    system_feed_join_clause,
    system_interest_kind_enabled_clause,
)

__all__ = [
    "HTTPException",
    "apply_resource_selection_payload",
    "apply_signal_candidate_selection_payload",
    "build_candidate_signal_quality_warnings",
    "build_content_item_id",
    "build_content_kind_selection_explain_payload",
    "build_editorial_content_item_preview_from_signal_candidate",
    "build_fallback_selection_blocker_payload",
    "build_hard_gate_safety_warnings",
    "build_interest_filter_count_summary",
    "build_resource_selection_explain_payload",
    "build_selection_diagnostics_payload",
    "build_selection_diagnostics_payload_from_counts",
    "build_selection_explain_payload",
    "build_selection_guidance_payload",
    "canonical_signal_candidate_family_expr",
    "canonical_signal_candidate_family_order_clause",
    "combined_content_items_select_sql",
    "editorial_content_select_sql",
    "effective_system_selected_expr",
    "effective_system_selection_decision_expr",
    "feed_eligible_signal_candidate_clause",
    "final_selection_join_clause",
    "get_selected_content_item_preview",
    "normalize_system_interest_selection_profile_payload",
    "parse_content_item_id",
    "primary_media_join_clause",
    "processed_signal_candidate_clause",
    "query_count",
    "resource_content_select_sql",
    "signal_candidate_observation_join_clause",
    "signal_candidate_preview_projection",
    "system_feed_join_clause",
    "system_interest_kind_enabled_clause",
]
