# ruff: noqa: F401
from __future__ import annotations

from signalops.api.main_route_prelude import (
    Any,
    ApiAppContext,
    ApiRouteDependencyValues,
    HTTPException,
    Literal,
    Mapping,
    Query,
    RESERVED_CONTEXT_KEYS,
    SEQUENCE_RUN_CANCELLABLE_STATUSES,
    SequenceQueueDispatchError,
    TASK_REGISTRY,
    _channel_read_model,
    _cluster_read_model,
    _content_analysis_backfill,
    _content_analysis_payloads,
    _content_analysis_policies,
    _content_analysis_read_model,
    _content_detail_read_model,
    _content_item_list_read_model,
    _content_selection_query_count,
    _dashboard_read_model,
    _llm_review_read_model,
    _notification_read_model,
    _reindex_read_model,
    _sequence_commands,
    _sequence_payloads,
    _sequence_read_model,
    _sequence_route_compat,
    _signal_candidate_list_read_model,
    _signal_candidate_residual_read_model,
    _system_interest_read_model,
    _user_interest_read_model,
    _user_match_read_model,
    _web_resource_read_model,
    apply_reindex_selection_profile_payload,
    apply_resource_selection_payload,
    apply_signal_candidate_selection_payload,
    as_json_bool,
    as_json_int,
    as_json_object,
    as_json_str,
    build_content_item_id,
    build_content_kind_selection_explain_payload,
    build_database_url,
    build_editorial_content_item_preview_from_signal_candidate,
    build_fallback_selection_blocker_payload,
    build_paginated_response,
    build_reindex_selection_profile_payload,
    build_resource_selection_explain_payload,
    build_route_deps,
    build_selection_diagnostics_payload,
    build_selection_diagnostics_payload_from_counts,
    build_selection_explain_payload,
    build_selection_guidance_payload,
    build_web_content_order_clause,
    build_web_content_search_clause,
    build_web_content_search_pattern,
    canonical_signal_candidate_family_expr,
    canonical_signal_candidate_family_order_clause,
    coerce_llm_review_cost_usd,
    combined_content_items_select_sql,
    create_api_app,
    default_max_entry_age_hours_for_adapter,
    dict_row,
    dispatch_sequence_run_job,
    editorial_content_select_sql,
    feed_eligible_signal_candidate_clause,
    final_selection_join_clause,
    get_selected_content_item_preview,
    infer_feed_ingress_adapter_strategy,
    is_fastapi_param_default,
    llm_review_accept_gray_zone_on_budget_exhaustion,
    llm_review_cost_usd_to_cents,
    llm_review_enabled,
    llm_review_month_start_utc,
    llm_review_monthly_budget_cents,
    normalize_optional_query_string,
    normalize_system_interest_selection_profile_payload,
    normalize_web_content_list_sort,
    normalize_web_content_search_query,
    parse_content_item_id,
    parse_cron_expression,
    primary_media_join_clause,
    processed_signal_candidate_clause,
    psycopg,
    query_all,
    query_one,
    resolve_feed_ingress_adapter_strategy,
    resolve_feed_ingress_max_entry_age_hours,
    resolve_pagination,
    resource_content_select_sql,
    signal_candidate_observation_join_clause,
    signal_candidate_preview_projection,
    strip_web_content_internal_fields,
    system_feed_join_clause,
    system_interest_kind_enabled_clause,
    uuid,
    with_resolved_channel_adapter_fields,
)

def normalize_optional_query_bool(value: Any) -> bool | None:
    if value is None or is_fastapi_param_default(value):
        return None
    return bool(value)


def query_count(sql: str, params: tuple[Any, ...] = ()) -> int:
    return _content_selection_query_count(sql, params, query_one_func=query_one)


__all__ = [
    "normalize_optional_query_bool",
    "query_count",
    "infer_feed_ingress_adapter_strategy",
    "default_max_entry_age_hours_for_adapter",
    "resolve_feed_ingress_adapter_strategy",
    "resolve_feed_ingress_max_entry_age_hours",
    "with_resolved_channel_adapter_fields",
    "is_fastapi_param_default",
    "normalize_web_content_list_sort",
    "normalize_web_content_search_query",
    "normalize_optional_query_string",
    "build_web_content_search_pattern",
    "build_web_content_search_clause",
    "build_web_content_order_clause",
    "strip_web_content_internal_fields",
    "as_json_object",
    "as_json_int",
    "as_json_bool",
    "as_json_str",
    "build_reindex_selection_profile_payload",
    "apply_reindex_selection_profile_payload",
]
