from __future__ import annotations

# ruff: noqa: F401

import os as _os
import uuid

import psycopg
from fastapi import HTTPException
from psycopg.rows import dict_row

from signalops.api.api_app import ApiAppContext, create_api_app
from signalops.api.database import build_database_url, query_all, query_one
from signalops.api.content_selection_read_model import (
    apply_resource_selection_payload,
    apply_signal_candidate_selection_payload,
    build_content_item_id,
    build_content_kind_selection_explain_payload,
    build_editorial_content_item_preview_from_signal_candidate,
    build_fallback_selection_blocker_payload,
    build_resource_selection_explain_payload,
    build_selection_diagnostics_payload,
    build_selection_diagnostics_payload_from_counts,
    build_selection_explain_payload,
    build_selection_guidance_payload,
    canonical_signal_candidate_family_expr,
    canonical_signal_candidate_family_order_clause,
    combined_content_items_select_sql,
    editorial_content_select_sql,
    feed_eligible_signal_candidate_clause,
    final_selection_join_clause,
    get_selected_content_item_preview,
    normalize_system_interest_selection_profile_payload,
    parse_content_item_id,
    primary_media_join_clause,
    processed_signal_candidate_clause,
    resource_content_select_sql,
    signal_candidate_observation_join_clause,
    signal_candidate_preview_projection,
    system_feed_join_clause,
    system_interest_kind_enabled_clause,
)
from signalops.api.llm_review_budget import (
    coerce_llm_review_cost_usd,
    llm_review_accept_gray_zone_on_budget_exhaustion,
    llm_review_cost_usd_to_cents,
    llm_review_enabled,
    llm_review_month_start_utc,
    llm_review_monthly_budget_cents,
)
from signalops.api.main_common import (
    apply_reindex_selection_profile_payload,
    as_json_bool,
    as_json_int,
    as_json_object,
    as_json_str,
    build_reindex_selection_profile_payload,
    build_web_content_order_clause,
    build_web_content_search_clause,
    build_web_content_search_pattern,
    default_max_entry_age_hours_for_adapter,
    infer_feed_ingress_adapter_strategy,
    is_fastapi_param_default,
    normalize_optional_query_bool,
    normalize_optional_query_string,
    normalize_web_content_list_sort,
    normalize_web_content_search_query,
    query_count,
    resolve_feed_ingress_adapter_strategy,
    resolve_feed_ingress_max_entry_age_hours,
    strip_web_content_internal_fields,
    with_resolved_channel_adapter_fields,
)
from signalops.api.main_content import (
    get_content_item,
    get_content_item_explain,
    get_resource_content_item,
    get_signal_candidate,
    get_signal_candidate_explain,
    get_web_resource,
    list_content_items,
    list_signal_candidate_residuals,
    list_signal_candidates,
    list_system_selected_content_items,
    list_system_selected_content_items_page,
    list_web_resources,
    list_web_resources_page,
    summarize_signal_candidate_residual_rows,
    summarize_signal_candidate_residuals,
    summarize_signal_candidate_selection_counts,
)
from signalops.api.main_content_analysis import (
    ContentAnalysisBackfillPayload,
    ContentAnalysisPolicyPayload,
    ContentAnalysisPolicyUpdatePayload,
    ContentFilterPolicyPayload,
    ContentFilterPolicyUpdatePayload,
    build_content_analysis_filter_clause,
    create_content_analysis_policy,
    create_content_filter_policy,
    get_content_analysis_policy,
    get_content_analysis_result,
    get_content_filter_policy,
    list_content_analysis_policies,
    list_content_analysis_results,
    list_content_entities,
    list_content_filter_policies,
    list_content_filter_results,
    list_content_labels,
    load_content_analysis_summary,
    normalize_content_analysis_status,
    normalize_content_analysis_subject_id,
    normalize_content_analysis_subject_type,
    normalize_content_analysis_type,
    normalize_content_filter_decision,
    preview_content_filter_policy,
    request_content_analysis_backfill,
    update_content_analysis_policy,
    update_content_filter_policy,
)
from signalops.api.main_observability import (
    get_channel,
    get_dashboard_summary,
    get_llm_budget_summary,
    get_llm_template,
    get_system_interest,
    list_channels,
    list_clusters,
    list_llm_templates,
    list_reindex_jobs,
    list_system_interests,
    list_user_interests,
    list_user_matches,
    list_user_notifications,
)
from signalops.api.main_sequence import (
    AgentSequenceCreatePayload,
    SequenceCancelPayload,
    SequenceConflictError,
    SequenceCreatePayload,
    SequenceDispatchError,
    SequenceManualRunPayload,
    SequenceNotFoundError,
    SequenceRetryRunPayload,
    SequenceUpdatePayload,
    SequenceValidationError,
    SignalCandidateEnrichmentRetryPayload,
    archive_sequence_definition,
    cancel_sequence_run,
    cancel_sequence_run_request,
    create_agent_sequence,
    create_agent_sequence_request,
    create_sequence,
    create_sequence_definition,
    create_sequence_run_request_for_trigger,
    create_sequence_run_request,
    delete_sequence,
    ensure_published_signal_candidate_retry_event,
    get_active_sequence_for_trigger,
    get_agent_sequence_tools,
    get_sequence,
    get_sequence_definition,
    get_sequence_plugins,
    get_sequence_run,
    get_sequence_run_status,
    get_sequence_run_task_runs,
    list_agent_sequence_tools,
    list_sequence_plugins,
    list_sequence_task_runs,
    list_sequences,
    list_sequences_page,
    normalize_sequence_cron,
    raise_sequence_http_exception,
    request_content_item_enrichment_retry_route,
    request_sequence_run,
    request_signal_candidate_enrichment_retry,
    request_signal_candidate_enrichment_retry_route,
    retry_sequence_run,
    retry_sequence_run_request,
    update_sequence,
    update_sequence_definition,
    validate_sequence_editor_state,
)
from signalops.api.main_compat import install_main_compat_exports
from signalops.api.route_deps import ApiRouteDependencyValues, build_route_deps

os = _os

API_MAIN_COMPAT_EXPORTS = (
    build_content_item_id,
    build_fallback_selection_blocker_payload,
    build_resource_selection_explain_payload,
    canonical_signal_candidate_family_order_clause,
    coerce_llm_review_cost_usd,
    editorial_content_select_sql,
    llm_review_accept_gray_zone_on_budget_exhaustion,
    llm_review_cost_usd_to_cents,
    llm_review_enabled,
    llm_review_month_start_utc,
    llm_review_monthly_budget_cents,
    resource_content_select_sql,
    system_interest_kind_enabled_clause,
)

_api_route_dependency_values = install_main_compat_exports(globals())


app = create_api_app(ApiAppContext(route_deps=build_route_deps(_api_route_dependency_values())))
