import type { McpResourceDefinition } from "./types";

export const scenarioResources: readonly McpResourceDefinition[] = [
  {
    uri: "signalops://guide/scenarios/sequences",
    name: "guide.scenarios.sequences",
    description: "Concrete MCP playbook for sequence drafting, execution, recovery, and archive decisions.",
    mimeType: "application/json",
    read: async () => ({
      objective:
        "Use this scenario when the job is to create, update, run, inspect, retry, cancel, or archive automation sequences through the SignalOps control plane.",
      startWith: [
        "Read signalops://admin/summary and signalops://sequences first.",
        "If the sequence does not exist yet, draft it with prompt sequence.draft before calling write tools.",
        "Prefer one sequence at a time; do not bundle unrelated automation changes into one session.",
      ],
      recommendedTools: {
        read: [
          "sequences.list",
          "sequences.read",
          "sequences.runs.read",
          "sequences.run_task_runs.list",
          "maintenance.reindex_jobs.list",
        ],
        write: [
          "maintenance.reindex.request",
          "sequences.create",
          "sequences.update",
          "sequences.run",
          "sequences.cancel_run",
          "sequences.retry_run",
          "sequences.archive",
        ],
      },
      intentRouting: [
        {
          phrases: [
            "старые статьи",
            "old signal_candidates",
            "historical signal_candidates",
            "existing content",
            "прогнать заново",
            "перепроверить по интересам",
            "selected шумит",
            "pass_through noise",
            "after Example C/templates/criteria changes",
          ],
          tool: "maintenance.reindex.request",
          payload: {
            indexName: "interest_centroids",
            jobKind: "backfill",
          },
          reason:
            "Selection replay recomputes current system-interest criteria evidence, interest_filter_results, and final_selection_results for existing content.",
        },
        {
          phrases: ["centroid index", "vector index", "only rebuild index", "только обновить индекс"],
          tool: "maintenance.reindex.request",
          payload: {
            indexName: "interest_centroids",
            jobKind: "rebuild",
          },
          reason: "Rebuild refreshes derived centroid/vector indexes and is not a historical selection replay.",
        },
        {
          phrases: ["NER", "entities", "sentiment", "category", "content labels", "filter evidence"],
          tool: "content_analysis.backfill.request",
          reason:
            "Content analysis backfill refreshes analysis/label/filter evidence only; it is not a replacement for selection replay.",
        },
      ],
      sessionFlow: [
        "Read the current sequence definition and recent runs before changing anything.",
        "Draft or review the task graph with sequence.draft when the intended workflow is non-trivial.",
        "For Default Reindex or other reindex maintenance work, use maintenance.reindex.request; do not manually call sequences.run unless you already have a valid reindex_job/event context.",
        "Do not use content_analysis.backfill.request as a substitute for selection replay; it does not recompute signal_candidate.match_criteria, interest_filter_results, or final_selection_results.",
        "Create or update the sequence, then run it in a bounded way and poll run state before deciding next actions.",
        "If a run fails, inspect the failed run details before retrying; treat retry as a recovery action, not a blind rerun.",
      ],
      destructiveCautions: [
        "Archive only after the run evidence and owning intent are clear.",
        "Cancel only active runs that should stop now; do not use cancel as a substitute for diagnosis.",
      ],
      verifyAfterWrite: [
        "Read the updated sequence back through sequences.read.",
        "Read the run state after run/cancel/retry and confirm the resulting status.",
      ],
    }),
  },
  {
    uri: "signalops://guide/scenarios/discovery",
    name: "guide.scenarios.discovery",
    description: "Concrete MCP playbook for Discovery vNext artifacts, inventory, policy, replay, and rollback.",
    mimeType: "application/json",
    read: async () => ({
      objective:
        "Use this scenario for vNext source discovery through typed artifacts, candidate acquisition, probing, source understanding, deterministic routing, source inventory, replay, and rollback.",
      startWith: [
        "Read signalops://discovery/runs, signalops://discovery/artifacts, signalops://discovery/candidates, signalops://discovery/source-inventory, and signalops://discovery/policies first.",
        "Create a Discovery vNext run before persisting artifacts or candidates.",
        "Use prompts discovery.artifact.review, discovery.source_understanding.review, and discovery.yield.review when artifact quality, policy fit, or routing evidence is unclear.",
      ],
      recommendedTools: {
        read: [
          "discovery.runs.list",
          "discovery.artifacts.list",
          "discovery.candidates.list",
          "discovery.source_inventory.list",
          "discovery.policies.list",
          "discovery.adapter_backlog.list",
          "discovery.feedback.list",
          "discovery.replay_runs.list",
          "discovery.rollback_groups.list",
          "discovery.eval_runs.list",
        ],
        write: [
          "discovery.runs.create",
          "discovery.runs.cancel",
          "discovery.brief.preview",
          "discovery.artifacts.create",
          "discovery.mega_loop.preview",
          "discovery.candidates.create",
          "discovery.probe.execute",
          "discovery.understand.preview",
          "discovery.route.preview",
          "discovery.routing.apply",
          "discovery.probation.handoff",
          "discovery.policies.activate",
          "discovery.replay.start",
          "discovery.rollback.prepare",
          "discovery.rollback.apply",
          "discovery.feedback.submit",
        ],
      },
      sessionFlow: [
        "Compile a DiscoveryBrief with domain-neutral constraints and persist only valid artifacts.",
        "Run bounded mega-loop/candidate acquisition; preserve rediscovery counts and query quality artifacts.",
        "Probe through fetchers-owned static/feed/sitemap semantics; browser probing requires explicit active probe policy.",
        "Build SourceUnderstanding from probe evidence and candidate facts, then route with the active routing policy.",
        "Historical yield is telemetry only; never use it as a keep/drop reason.",
        "Adapter needs go to adapter_backlog; accepted probation handoff must use source_channels and source channel sync outbox discipline.",
        "Use replay before changing policy and prepare rollback groups before destructive rollback.",
      ],
      destructiveCautions: [
        "Destructive rollback requires write.destructive scope and confirm=true.",
        "Do not delete shared source_channels, source_channel_runtime_state, outbox, fetcher-owned content/fetch tables, web_resources, or downstream filtering state as Discovery cleanup.",
      ],
      verifyAfterWrite: [
        "Read back the updated run, artifact, candidate, source inventory record, policy, replay run, rollback group, or feedback event after every mutation.",
        "After discovery.runs.create, treat the result as queued until a worker or replay result updates it.",
        "After probation handoff, confirm the resulting source_channel and source.channel.sync.requested outbox event.",
        "Before the final discovery report, read discovery.runs.list, discovery.artifacts.list, discovery.source_inventory.list, and discovery.policies.list.",
      ],
    }),
  },
  {
    uri: "signalops://guide/scenarios/discovery-live-gap-hunting",
    name: "guide.scenarios.discovery-live-gap-hunting",
    description: "MCP-only live Discovery vNext gap-hunting playbook for domain-neutral operator proofs.",
    mimeType: "application/json",
    read: async () => ({
      objective:
        "Use this scenario to prove and debug the real Discovery vNext operator flow through MCP only, across multiple domain-neutral signal families.",
      startWith: [
        "Use MCP initialize, tools/list, resources/list and prompts/list to prove the client can see the needed surfaces.",
        "Read discovery, funnel-calibration and operating-model guides before writes.",
        "Run operator.funnel.audit, operator.funnel.autoplan, operator.funnel.iteration.recommend and discovery.source_families.coverage before creating live interests.",
      ],
      scenarioPacks: [
        "public_procurement",
        "security_advisories",
        "policy_regulatory",
        "research_grants",
        "software_changelogs",
      ],
      requiredMcpSurfaces: [
        "system_interests.create/read/list/compile_status.list",
        "llm_templates.list/read/create/update",
        "discovery.runs.execute/read/list",
        "discovery.run_steps.list",
        "discovery.query_attempts.list",
        "discovery.artifacts.list/read",
        "discovery.candidates.list/read",
        "discovery.probe.plan_preview",
        "discovery.probe.execute",
        "discovery.understand.preview",
        "discovery.routing.apply",
        "discovery.probation.handoff",
        "discovery.replay.start",
        "discovery.feedback.submit",
        "operator.report.verify",
      ],
      gapClasses: [
        "missing_mcp_surface",
        "schema_gap",
        "runtime_gap",
        "diagnostic_gap",
        "policy_gap",
        "provider_gap",
      ],
      successCriteria: [
        "Every product mutation uses MCP and is followed by an MCP read-back.",
        "At least three scenario packs produce candidates or explainable live provider failures.",
        "Query attempts include live provider metadata.",
        "Persisted artifacts, candidates, inventory, monitoring state, observations or adapter backlog are visible through MCP diagnostics.",
      ],
      evidencePolicy:
        "Live evidence is retained by default for manual inspection. Cleanup must be explicit and separate from the proof.",
    }),
  },
  {
    uri: "signalops://guide/scenarios/funnel-calibration",
    name: "guide.scenarios.funnel-calibration",
    description: "Concrete MCP playbook for turning a working manual/example bundle into generic product-funnel calibration.",
    mimeType: "application/json",
    read: async () => ({
      objective:
        "Use this scenario when a prior manual setup, example bundle, JSON asset, or admin-tuned configuration worked better than the current discovery/product flow.",
      startWith: [
        "Read the current runtime state first: system interests, compile status, LLM templates, channel bottlenecks, signal_candidate residuals, selected content, and discovery targets.",
        "Treat the reference bundle as calibration evidence, not canonical runtime truth and not code input.",
        "Do not assume the operator wants the reference domain rerun. If the request is to improve the system, produce reusable funnel-design rules and prompt/admin guidance before any product mutations.",
        "Compare the reference with current MCP state before creating new interests, templates, targets, or channels.",
      ],
      recommendedTools: {
        read: [
          "operator.funnel.audit",
          "operator.funnel.autoplan",
          "operator.funnel.iteration.recommend",
          "system_interests.list",
          "system_interests.read",
          "system_interests.compile_status.list",
          "templates.duplicates.audit",
          "llm_templates.list",
          "llm_templates.read",
          "channels.bottlenecks.summary",
          "channels.bottlenecks.list",
          "signal_candidates.residuals.summary",
          "signal_candidates.residuals.list",
          "content_items.list",
          "discovery.runs.list",
          "discovery.artifacts.list",
          "discovery.source_inventory.list",
          "discovery.policies.list",
          "operator.report.verify",
        ],
        writeFollowThrough: [
          "system_interests.create",
          "system_interests.update",
          "llm_templates.create",
          "llm_templates.update",
          "discovery.runs.create",
          "discovery.artifacts.create",
          "discovery.policies.activate",
          "channels.bulk_onboard.plan",
          "channels.bulk_onboard.apply",
          "maintenance.reindex.request",
        ],
      },
      extractFromReference: [
        "the objective and buyer/actor model: who creates the signal and what decision or pain it implies",
        "source capability classes and provider shapes that actually fed the funnel",
        "signal families, not just keywords",
        "positive prototypes and near-miss negative prototypes",
        "candidate uplift positive and negative cue groups",
        "allowed content kinds and strictness/review policy",
        "LLM review scope and guardrails for wrapper/noise pages",
        "provider types that require adapters or mapping instead of fake RSS/website rows",
      ],
      portableFunnelSpec: {
        requiredSections: [
          "objective and excluded outcomes",
          "actor/buyer model and evidence threshold",
          "signal families with positive prototypes",
          "near-miss negatives and must-not cues",
          "source capability matrix by provider shape",
          "working-noisy versus broken-source policy",
          "candidate or gray-zone recovery policy",
          "final selection and web-visibility proof gates",
          "observation budget for rare low-yield sources",
          "adapter or mapping gaps",
        ],
        sourceCapabilityMatrix: [
          "direct-intent sources: posts, notices, tenders, asks, support requests, or listings authored by the buyer or controlling organization",
          "context sources: funding, hiring, policy, incident, award, roadmap, or market signals that may create follow-up hypotheses but do not prove final demand alone",
          "community/hidden-signal sources: forum, social, Q&A, or discussion feeds that stay monitor/claim oriented unless the author and ask are clear",
          "directory/replacement sources: source lists, portals, sitemaps, newsletters, or related feeds used to expand acquisition breadth",
          "adapter-required sources: API-like, ATS, marketplace, repository, or authenticated sources that must not be disguised as RSS/website",
        ],
        consistencyChecks: [
          "Each active system interest should map to a named signal family, not a one-off keyword pile.",
          "Every positive cue family should have a paired near-miss negative family.",
          "For weak or short-form signals, item-level buyer/project evidence can be stronger than broad semantic similarity; configure candidate cue groups for buyer ask, project object, deliverable/scope, budget/timeline, and contact/procurement evidence instead of relying only on embedding proximity.",
          "Do not use single ambiguous words such as event, guide, fixed-price, hiring, or best practices as universal negatives; make them phrase-level negatives that only fire when buyer/project evidence is absent.",
          "LLM review prompts must use the specific interest/criterion as the authoritative frame, not broad topic similarity.",
          "High source semantic fit can extend observation, but cannot select or publish content.",
          "Low yield from a working rare-signal source is expected; transport/provider-shape failure is a repair problem.",
        ],
      },
      sessionFlow: [
        "Call operator.funnel.audit first when the client supports tools. The audit is read-only and returns portableFunnelSpec, DB-backed liveStateSummary, drift findings, and recommended MCP actions.",
        "First classify the current gap: source acquisition, provider-shape failure, transport bottleneck, projection/dedupe, semantic filtering, gray-zone hold, or LLM review behavior.",
        "Before running discovery, write down the portable funnel spec and use it as the checklist for interests, templates, source capability classes, adapter gaps, and proof.",
        "Use source expansion for source-pool gaps and template/interest tuning only for repeated downstream evidence patterns.",
        "For rare-signal funnels, prefer broad working source pools plus strict independent filtering; low yield alone is not a broken source.",
        "Coverage-first funnels should retain working noisy, low-yield, and negative-control useful channels as measured acquisition inventory. Only explicit operator action should disable a semantically plausible working channel; automatic handling should label, measure, slow cadence, repair technical blockers, or mark adapter/access requirements.",
        "Use discovery.source_families.coverage and operator.report.verify reportKind=source_family_balance to prove source-family balance before judging whether the funnel is complete.",
        "Use operator.funnel.autoplan for a read-only source-family/query/polling/repair/selection plan, then operator.funnel.iteration.recommend for the next bounded MCP action.",
        "If the gap is gray-zone hold after changed interests/templates or a failed full replay, follow operator.tuning.recommend and run bounded maintenance.reindex.request chunks with explicit docIds before changing selection criteria.",
        "Avoid broad hard gates early. Use must-have terms or time windows only when a marker is truly mandatory and replay/read-back proves recall is acceptable.",
        "For rare-signal baselines, treat empty must_have_terms and empty/null time_window_hours as the default starting point; recency goals belong in report/product-test acceptance unless the marker is truly part of the signal.",
        "Use negative cues and LLM guardrails to reject wrapper, seller-authored, navigation, directory, generic-advice, training, and jobs-only noise instead of adding broad positive hard gates.",
        "Selected content is the only web truth. If selected rows include context-only/noise, use operator.selection.precision_audit and selection tuning/replay to demote them; do not introduce a second public/private selected layer.",
        "When project-detail listings, support threads, or forum asks are short, tune candidateSignals so several independent item-level cues can recover the item into gray/LLM/hold even if semantic prototype similarity is below the usual near-threshold. This recovery must never select or publish content by itself.",
        "For marketplace/forum project pages, prefer positive cue groups like buyer_ask, project_object, deliverable_scope, budget_or_timeline, vendor_search, and integration_or_migration. Pair them with precise negatives such as seller-authored profile, category/navigation wrapper, generic advice without buyer project, and internal job opening without contractor/vendor ask.",
        "For executable search/aggregator lanes, treat search-ad click URLs, category/tag/search wrappers, ranking/list posts, seller-authored landing pages, generic how-to/why/guide signal_candidates, and jobs-only pages as acquisition noise unless the item itself contains buyer/project/vendor-search evidence.",
        "For weak-signal domains, prefer many technically working noisy sources plus strict downstream filtering. Repair transport/provider-shape bottlenecks separately from semantic quality, and do not loosen selected-content rules to compensate for low-yield sources.",
        "Do not mask API/social/ATS/StackExchange/GitHub/marketplace sources as RSS or website rows. Mark them adapter_required/api_mapping_required/needs_config or find validated alternatives.",
        "Use discovery.brief.preview, discovery.mega_loop.preview, discovery.candidates.create, discovery.probe.execute, discovery.understand.preview, discovery.route.preview, and source inventory reads to prove whether the funnel covers the places where the signal can actually appear.",
        "Use discovery.adapter_backlog.list/read and routing decisions to separate official/free, configured, access-gated, and unsupported acquisition lanes.",
        "Use Discovery vNext candidates and routing when closed or access-gapped source families need executable search coverage. Keep indirect/search channels acquisition-only unless a first-party source is actually onboarded. For local research without external keys or SearXNG, use ddgs_search.",
        "For marketplace/forum sources, check marketplace_extraction_quality before tuning: project-detail extraction must reject category/navigation/profile/listing-wrapper noise and preserve buyer/project fields when available.",
        "Apply one bounded change at a time, then verify affected entities and selection/web-visible counts through MCP.",
      ],
      whenToMutate: [
        "If the operator asks for research, design, or system improvement, return the portable funnel spec and recommended generic MCP/admin prompt changes without writing domain config.",
        "If the operator asks for a product test or calibration run, apply bounded MCP/admin config only after current state read-back and explicit scope is clear.",
        "If the reference shows API-like sources, record adapter requirements and alternative-finder work instead of forcing onboarding.",
      ],
      invariants: [
        "Reference bundles do not become runtime truth until applied through MCP/admin configuration and read back from the database.",
        "Domain-specific vocabulary belongs in templates, interests, targets, source config, and tests, not hardcoded runtime logic.",
        "Source health and vNext routing telemetry can improve acquisition and monitoring, but they must not directly select, rank, escalate, or publish content.",
        "Selected row counts and public content-item counts can differ because canonical/public projection and dedupe are separate product stages.",
      ],
      verifyAfterWrite: [
        "Read changed system interests or LLM templates back through MCP.",
        "If interest/template semantics changed for existing content, queue maintenance.reindex.request with jobKind=backfill and verify the job/run state. For retained DBs or timeout-prone replays, pass bounded payload.options.docIds chunks and parentReindexJobId/reason.",
        "For new or repaired sources, use channels.bulk_onboard.verify, fetch_runs.list, and channels.bottlenecks.summary/list.",
        "For source inventory or adapter backlog claims, call operator.report.verify with reportKind=source_family_balance or discovery_run.",
        "For coverage-first source-family claims, call operator.report.verify with reportKind=source_family_balance.",
        "For executable search lanes, call operator.report.verify with reportKind=indirect_search_execution.",
        "For marketplace/forum extraction quality, call operator.report.verify with reportKind=marketplace_extraction_quality.",
        "For final claims, call operator.report.verify with selection, source_bottleneck, channel_onboarding, or discovery_run as applicable.",
        "For calibration claims, call operator.report.verify with reportKind=funnel_calibration and includeSamples=true.",
      ],
    }),
  },
  {
    uri: "signalops://guide/scenarios/selection-calibration",
    name: "guide.scenarios.selection-calibration",
    description:
      "Concrete MCP playbook for zero selected signals, semantic rejection, missing LLM calls, and bounded selection calibration.",
    mimeType: "application/json",
    read: async () => ({
      objective:
        "Use this scenario when an external MCP client sees 0 selected signals, semantic_rejected/no_system_match, absent LLM spend, or confusing live Discovery failures and needs to classify the failing layer before changing configuration.",
      startWith: [
        "Read signalops://guide/playbooks/strict-next-steps and follow its read-back -> classify -> bounded write -> bounded replay -> verify sequence.",
        "Read admin.summary.get or signalops://admin/summary first.",
        "Read signalops://guide/reference/selection-evidence-semantics before interpreting hard gates, backfill counters, LLM spend, or gray-zone changes.",
        "Read signalops://guide/reference/hidden-signal-evidence-lanes before recommending must_have_terms, short_tokens_required, strictness changes, or candidateSignals cue repairs.",
        "Read operator.selection.dashboard and compare filterReasonBreakdown.filterRows to distinctCandidateCount before estimating candidate impact.",
        "Read signal_candidates.residuals.summary, then signal_candidates.residuals.list for the dominant blocker bucket.",
        "Inspect 1-3 representative cases with signal_candidates.explain before proposing any write.",
        "Read the affected system_interests.read result and system_interests.compile_status.list so candidateSignals, profile policy, and compile errors are visible.",
        "Call operator.tuning.recommend before changing interests, templates, policies, or sources.",
      ],
      recommendedTools: {
        read: [
          "admin.summary.get",
          "signal_candidates.residuals.summary",
          "signal_candidates.residuals.list",
          "signal_candidates.explain",
          "system_interests.read",
          "system_interests.compile_status.list",
          "llm_budget.summary",
          "operator.system.health",
          "operator.issue.explain",
          "operator.tuning.recommend",
          "maintenance.reindex_jobs.list",
          "operator.effect.verify",
          "operator.report.verify",
        ],
        boundedWrites: [
          "system_interests.update",
          "llm_templates.update",
          "content_filter_policies.update",
          "content_analysis_policies.update",
          "channels.update",
          "discovery.policies.activate",
          "maintenance.reindex.request",
        ],
      },
      diagnosticBranches: [
        {
          branch: "acquisition_gap",
          evidence:
            "No or too few signal_candidates exist for the expected source family; source inventory, query attempts, probes, or channels show missing acquisition.",
          response:
            "Repair Discovery/source coverage through discovery and channel tools. Do not loosen selection until acquisition evidence exists.",
        },
        {
          branch: "channel_or_fetch_failure",
          evidence:
            "channels.read/list, fetch_runs.list, web_resources.list, or channels.bottlenecks.* show transport/provider-shape failures.",
          response:
            "Treat RSS/channel volume as acquisition evidence only. Fix provider config, polling, alternatives, or adapter backlog before judging selection.",
        },
        {
          branch: "high_filter_rows_low_distinct_candidates",
          evidence:
            "operator.selection.dashboard shows large filterRows for a reason but much smaller distinctCandidateCount because candidates are evaluated across many criteria.",
          response:
            "Do not multiply row counts into candidate impact. Inspect 10-30 representative rejected candidates, identify false-negative patterns, then repair only the specific config/heuristic proven by samples.",
        },
        {
          branch: "semantic_rejected/no_system_match",
          evidence:
            "Representative signal_candidates.explain rows show no matching system criterion or semantic rejection before gray-zone/LLM review.",
          response:
            "First classify signalVisibility. For hidden_intent or unknown, keep must_have_terms=[] and short_tokens_required=[]; use candidateSignals-first recovery with literal observable cue fragments, signal families, source/context evidence, near-miss negatives, and bounded replay. llmReviewMode=always does not bypass semantic rejection.",
        },
        {
          branch: "gray_zone_or_hold",
          evidence:
            "Residuals or holds show gray_zone_hold, candidate_signal_hold, buyer_intent_hold, project_intent_hold, or llm_review_pending.",
          response:
            "Inspect holds summary/list/explain, then replay only bounded docIds chunks. Prefer 25 items and never more than 50 when LLM reviews may run.",
        },
        {
          branch: "llm_review_diagnostic",
          evidence:
            "LLM spend is zero or unexpectedly low.",
          response:
            "Classify llm_review_disabled, budget_exhausted, no_pending_gray_zone, worker_not_running, provider_credentials_missing, or semantic rejection before LLM. 0 LLM spend is not proof the LLM path is broken.",
        },
        {
          branch: "discovery_runtime_credentials_missing",
          evidence:
            "Live Discovery returns runtime_credentials_missing or provider readiness errors.",
          response:
            "Treat this as preflight/not_applicable for live-provider proof. Do not tune maxRunCostCents or broaden sources to fix absent credentials.",
        },
      ],
      sessionFlow: [
        "Classify the failure layer before mutations: acquisition gap, channel/fetch failure, semantic_rejected/no_system_match, gray-zone/hold, LLM review issue, or Discovery runtime credentials missing.",
        "Classify signalVisibility before hard gates: explicit_marker, hidden_intent, mixed, or unknown.",
        "For hidden_intent or unknown, empty hard gates are baseline. Do not add must_have_terms or short_tokens_required as first repair.",
        "For mixed signals, split lane-like config first: explicit marker lane, hidden intent lane, source context lane, and negative-control lane as needed.",
        "Check operator.selection.dashboard staleProfileDiagnostics before trusting residual counters or gray-zone collapse.",
        "For 0 selected with existing signal_candidates, inspect residuals and filterReasonBreakdown before adding sources. More RSS may increase acquisition volume without proving selected-signal recall.",
        "For semantic_rejected/no_system_match, read one affected interest and compile status, then compare representative candidate evidence with the interest's signal families and candidateSignals.",
        "If the interest is a keyword pile or only short positive_texts, rewrite it into signal families, real positive prototypes, near-miss negatives, candidate positive cue groups, and candidate negative cue groups. For hidden/operational signals, do not recommend adding positive terms as the main repair.",
        "For candidateSignals, group.name is a conceptual label and group.cues are literal observable fragments; replace snake_case/id-like cue labels with text seen in representative candidates.",
        "Treat backfill criteriaMatches/interestMatches and filterReasonCounts as processed-row counters, not distinct candidates and not selected-signal proof.",
        "If gray_zone collapses, classify stale replay, hard-filter collapse, residual distribution, rejected samples, selected quality, and hold quality before calling it precision improvement.",
        "Apply at most one bounded write. Do not mass edit 30 interests, mass-set strictness=broad, or rewrite LLM templates before a representative candidate proves the needed change.",
        "For wrapper_directory_noise, time_window, must_not, content_kind and other hard filters, never recommend global disable from row counts alone; sample first and replay explicit docIds.",
        "Read the changed entity back through MCP. If the read-back does not show the intended policy/template/interest fields, stop and fix the write path.",
        "Use only canonical system-interest write fields: candidate_positive_signals, candidate_negative_signals, selection_profile_llm_review_mode, and allowed_content_kinds.",
        "Replay only explicit docIds from the inspected residual bucket. Use maintenance.reindex.request with bounded payload.options.docIds chunks and a reason tied to the calibration.",
        "After replay, use maintenance.reindex_jobs.list, operator.effect.verify, and operator.report.verify reportKind=selection or selection_tuning before the next change.",
      ],
      antiPatterns: [
        "Starting 0 selected diagnosis with mass strictness=broad.",
        "Editing many interests or LLM templates without 1-3 representative signal_candidates.explain rows.",
        "Treating 0 LLM spend as an LLM outage before checking no_pending_gray_zone or semantic rejection before LLM.",
        "Using only short keyword phrases in positive_texts instead of representative positive prototypes.",
        "Recommending positive-term expansion for hidden operational signals before candidateSignals, policy evidence, and near-miss negatives.",
        "Reporting gray-zone collapse as more precise without selected and near-miss sample proof.",
        "Treating criteriaMatches/interestMatches as selected-signal proof.",
        "Treating filterReasonCounts as unique candidate counts.",
        "Globally removing wrapper/source-navigation filters without representative false-negative samples.",
        "Using stale report channel counts or historical/transient fetch failures as current source health.",
        "Treating broad strictness as a fix for missing item-level evidence.",
        "Using OR must_have_terms as if it were hidden-signal safe.",
        "Using short_tokens_required as a replacement OR keyword list.",
        "Using candidateSignals cues that are concept labels rather than literal text fragments.",
        "Adding more RSS/channel rows as selection proof.",
        "Masking API/portal/search sources as RSS/website instead of adapter_required or api_mapping_required.",
        "Using discovery.brief.preview as a workaround for domain_contamination or persisted DiscoveryBrief validation.",
        "Reporting intended system-interest profile/candidateSignals writes before readBackVerification proves persisted state.",
        "Skipping MCP read-back and bounded replay proof after a write.",
      ],
      invariants: [
        "llmReviewMode=always is not a bypass for semantic_rejected/no_system_match.",
        "candidateSignals can recover items into gray/hold/review paths but must not select or publish content by themselves.",
        "Domain examples are calibration evidence only; product behavior must be changed through admin/MCP configuration and read-back.",
        "Live Discovery without runtime credentials is preflight/not_applicable, not a budget-tuning task.",
      ],
      verifyAfterWrite: [
        "Read the changed system interest, LLM template, content policy, channel, or Discovery policy back through MCP.",
        "Replay only bounded docIds from the diagnosed residual bucket.",
        "Verify replay completion through maintenance.reindex_jobs.list.",
        "Call operator.report.verify with reportKind=selection_tuning or selection, and includeSamples=true when reporting calibration success.",
      ],
    }),
  },
  {
    uri: "signalops://guide/scenarios/system-interests",
    name: "guide.scenarios.system-interests",
    description: "Concrete MCP playbook for creating, refining, archiving, and deleting system interests.",
    mimeType: "application/json",
    read: async () => ({
      objective:
        "Use this scenario for editorial/operator interest maintenance when SignalOps needs a bounded monitoring intent for a topic, audience, or signal family.",
      startWith: [
        "Read signalops://system-interests first to avoid duplicating an existing interest.",
        "Use prompt system_interest.create to draft the initial payload when the topic needs careful inclusion/exclusion framing.",
        "For 0 selected or semantic_rejected/no_system_match, read signalops://guide/scenarios/selection-calibration before changing the interest.",
        "For hidden, mixed, rare or unknown signals, read signalops://guide/reference/hidden-signal-evidence-lanes before adding hard gates.",
      ],
      recommendedTools: {
        read: ["system_interests.list", "system_interests.read"],
        write: [
          "system_interests.create",
          "system_interests.update",
          "system_interests.archive",
          "system_interests.delete",
        ],
      },
      sessionFlow: [
        "Read nearby interests and confirm the new topic is genuinely distinct.",
        "If the interest is part of a calibrated funnel, compare it with the reference signal family before creating another broad or overlapping interest.",
        "Draft signal families, representative positive prototypes, near-miss negative prototypes, candidate positive/negative cue groups, allowed content kinds and scope before creating the interest.",
        "Avoid short keyword piles in positive_texts; each positive prototype should describe item-level evidence that would justify a match.",
        "For candidateSignals, group cues by evidence role, such as buyer ask, project object, deliverable/scope, budget/timeline, source authority, and near-miss negative patterns.",
        "For candidateSignals, group.name is the conceptual label; group.cues must be literal observable text fragments that can appear in candidate title/lead/body.",
        "For hidden/unknown signals, keep must_have_terms=[] and short_tokens_required=[] as the baseline. For explicit marker lanes, add hard gates only after mandatory-marker proof and bounded replay.",
        "For mixed signals, split lane-like interests/criteria/config-pack entries so hidden lanes do not inherit explicit-marker gates.",
        "For rare-signal funnels, prefer negative cues and LLM review over broad must-have gates unless a marker is truly mandatory.",
        "Use newline-separated strings or string arrays for list-like fields. For allowed_content_kinds, use concrete entries such as editorial, listing, and document, not one combined text value.",
        "If a write tool returns an MCP error, stop and correct the payload; do not report creation until system_interests.read or list proves the new entity exists.",
        "Update only one interest at a time so resulting monitoring behavior remains explainable.",
      ],
      destructiveCautions: [
        "Archive before delete when the operator may need a recoverable historical trail.",
        "Delete only with explicit confirmation and only when the interest is clearly obsolete or erroneous.",
      ],
      verifyAfterWrite: [
        "Read the interest back through system_interests.read.",
        "Check system_interests.compile_status.list when candidateSignals, profile policy, or template-linked fields changed.",
        "Re-read the interests list to confirm the intended lifecycle state.",
      ],
    }),
  },
  {
    uri: "signalops://guide/scenarios/llm-templates",
    name: "guide.scenarios.llm-templates",
    description: "Concrete MCP playbook for LLM template drafting, bounded edits, archive, and delete decisions.",
    mimeType: "application/json",
    read: async () => ({
      objective:
        "Use this scenario for operator-owned LLM template maintenance, especially when tuning prompt text, model settings, or template lifecycle state.",
      startWith: [
        "Read signalops://templates/llm first and inspect the current template before editing.",
        "Keep changes bounded to one template and one intent change per session whenever possible.",
      ],
      recommendedTools: {
        read: ["llm_templates.list", "llm_templates.read"],
        write: [
          "llm_templates.create",
          "llm_templates.update",
          "llm_templates.archive",
          "llm_templates.delete",
        ],
      },
      sessionFlow: [
        "Read the current template body and metadata first.",
        "State the exact behavior change being sought before editing prompt text or configuration.",
        "Prefer incremental edits over wholesale rewrites unless the template is clearly being replaced.",
      ],
      destructiveCautions: [
        "Archive before delete when you may need to preserve lineage or compare prompt behavior later.",
        "Do not widen template authority or implied scope silently; document why the template changed.",
      ],
      verifyAfterWrite: [
        "Read the updated template back through llm_templates.read.",
        "Confirm list visibility or lifecycle status through signalops://templates/llm.",
      ],
    }),
  },
  {
    uri: "signalops://guide/scenarios/channels",
    name: "guide.scenarios.channels",
    description: "Concrete MCP playbook for channel creation, tuning, verification, and removal.",
    mimeType: "application/json",
    read: async () => ({
      objective:
        "Use this scenario for source-channel onboarding and maintenance, including Discovery vNext probation handoff follow-up, metadata correction, and bounded cleanup.",
      startWith: [
        "Read signalops://channels first to check whether the source already exists or overlaps with an existing channel.",
        "When a channel comes from Discovery vNext probation handoff, preserve SourceUnderstanding, RoutingDecision, source inventory, and outbox evidence before making manual edits.",
      ],
      recommendedTools: {
        read: [
          "channels.list",
          "channels.read",
          "channels.bulk_onboard.plan",
          "channels.alternatives.plan",
          "channels.bulk_onboard.verify",
          "fetch_runs.list",
          "web_resources.list",
        ],
        write: [
          "channels.create",
          "channels.update",
          "channels.bulk_onboard.apply",
          "channels.alternatives.start",
          "channels.delete",
        ],
      },
      sessionFlow: [
        "Read existing channels and identify whether this is a new source, a correction, or a cleanup action.",
        "For more than one explicit source, use channels.bulk_onboard.plan first; inspect create/update/duplicate/invalid/mismatch/override rows before applying.",
        "For RSS rows that look like website roots/pages or structurally failing channels, run channels.bottlenecks.summary/list and channels.alternatives.plan; valid RSS candidates must come from feed-probe evidence or a feed-like URL.",
        "When RSS fails with auth_or_blocked_403, not_acceptable_406, malformed_feed, html_instead_of_feed, gone_404, or equivalent error text, review channels.alternatives.plan website_fallback candidates. They are needs_probe candidates only, not auto-created channels.",
        "If a website_fallback candidate is safe, run channels.bulk_onboard.plan with providerType=website, then channels.bulk_onboard.apply, then channels.bulk_onboard.verify. Do not create a website channel blindly from an invalid RSS URL.",
        "Apply only the current planFingerprint. Use confirm=true for updates and overrideReason only when source evidence justifies a provider mismatch override.",
        "For promoted sources, compare promoted metadata with the source evidence before broadening tags or trust.",
        "Apply bounded edits, then verify the resulting channel state and any downstream list visibility.",
        "For website channels, verify acquisition through fetch_runs.list and web_resources.list before judging signal_candidate/selection outcomes.",
      ],
      destructiveCautions: [
        "Delete only with explicit confirmation and only when the channel is invalid, duplicate, or intentionally removed.",
      ],
      verifyAfterWrite: [
        "Read the channel back through channels.read.",
        "For website channels, inspect web_resources with projection=all, then compare projection=resource_only and projection=projected.",
        "Do not treat projected-but-rejected rows as channel creation failure; that is downstream selection/filtering evidence.",
        "Re-read signalops://channels to confirm the catalog reflects the intended change.",
      ],
    }),
  },
  {
    uri: "signalops://guide/scenarios/signal_candidate-diagnostics",
    name: "guide.scenarios.signal_candidate-diagnostics",
    description: "Concrete MCP playbook for signal_candidate residual analysis and evidence-based tuning.",
    mimeType: "application/json",
    read: async () => ({
      objective:
        "Use this scenario to understand why editorial observations did not reach selected content and to produce bounded tuning recommendations from signal_candidate/content evidence.",
      startWith: [
        "Read signalops://signal-candidates/residuals-summary first to identify the dominant blocker buckets.",
        "Use signal_candidates.residuals.list to inspect representative rows for one blocker at a time.",
        "Inspect the same case through signal_candidates.explain and, when relevant, content_items.explain to compare editorial observation truth with selected/public truth.",
      ],
      recommendedTools: {
        read: [
          "signal_candidates.list",
          "signal_candidates.read",
          "signal_candidates.explain",
          "signal_candidates.residuals.list",
          "signal_candidates.residuals.summary",
          "signal_candidates.holds.summary",
          "signal_candidates.holds.list",
          "signal_candidates.holds.explain",
          "content_items.list",
          "content_items.read",
          "content_items.explain",
          "operator.selection.precision_audit",
          "operator.tuning.recommend",
          "maintenance.reindex_jobs.list",
          "operator.report.verify",
          "operator.effect.verify",
        ],
      writeFollowThrough: [
        "maintenance.reindex.request",
        "system_interests.update",
        "llm_templates.update",
        "discovery.artifacts.create",
        "discovery.policies.activate",
        ],
      },
      sessionFlow: [
        "Diagnose residual buckets before drilling into single examples.",
        "Separate technical filtering, semantic rejection, gray-zone hold, and review-pending cases before proposing config changes.",
        "For semantic_rejected/no_system_match, do not begin with broad strictness, LLM template rewrites, positive-term expansion, or more RSS volume. Inspect the candidate explanation, the affected system interest, compile status, and candidateSignals, then tune one interest from repeated evidence.",
        "For hidden/operational signals, use candidateSignals, policy evidence, and near-miss negatives before changing positive_texts; positive_texts should remain representative prototypes, not keyword recovery.",
        "Treat criteriaMatches/interestMatches as backfill processor counters. Use final_selection_results, content_items, residual samples, and operator.report.verify for selected-signal proof.",
        "Do not infer improvement from gray_zone collapse alone; inspect rejected samples, hold quality, replay freshness, and selected/near-miss samples.",
        "If selected count is 0, run signalops://guide/scenarios/selection-calibration before any mass write.",
        "For gray_zone_hold/candidate_signal_hold, call operator.tuning.recommend with domain=selection, objective=increase_recall, residualBucket=gray_zone_hold, then inspect signal_candidates.holds.summary/list/explain before replay.",
        "If LLM spend is 0, classify llm_review_disabled, budget_exhausted, no_pending_gray_zone, worker_not_running, provider_credentials_missing, or semantic rejection before LLM before changing budgets or templates.",
        "When selected content itself is noisy, call operator.selection.precision_audit, then tune negative/veto cues or candidateSignals through MCP/admin and replay only the weak selected docIds in bounded chunks.",
        "Treat context candidate signals as diagnostics. Replay buyer_intent/project_intent holds first, in chunks of 25 by default and never more than 50 when LLM reviews may run.",
        "After a bounded replay chunk, wait for maintenance.reindex_jobs.list to show completed or failed, then run operator.report.verify reportKind=selection, operator.report.verify reportKind=selection_hold_quality, and operator.effect.verify before the next chunk or any interest/template edit.",
        "Tune one interest, template, or discovery target policy at a time and keep recommendations bounded to repeated evidence patterns.",
        "After any mutation outside this read-first flow, re-read the affected entity through MCP before making the next recommendation.",
      ],
      invariants: [
        "Downstream signal_candidate/content diagnostics may inform operator prompts and decisions, but they must not become direct discovery auto-approval inputs.",
        "Do not treat one residual row as enough evidence for broad policy changes; look for repeated patterns inside the same bucket.",
        "A bounded replay chunk is a recalculation step, not proof of improved quality. Report impact only from operator.report.verify and operator.effect.verify read-back.",
        "There is no separate public selected gate: final_selection_results selected rows are what web should show. Fix noisy selected rows at the selection pipeline/config layer.",
        "Source priors, channel health, and source bottlenecks can explain acquisition or repair, but they must not select, rank, escalate, or publish signal_candidate/content items.",
        "llmReviewMode=always does not bypass semantic_rejected/no_system_match.",
      ],
    }),
  },
  {
    uri: "signalops://guide/scenarios/observability",
    name: "guide.scenarios.observability",
    description: "Concrete MCP playbook for read-only operator diagnosis across admin summary, budgets, web resources, and fetch runs.",
    mimeType: "application/json",
    read: async () => ({
      objective:
        "Use this scenario for read-only operator diagnosis when the goal is to understand current system state, recent runtime behavior, or bounded evidence before deciding whether a write is needed.",
      startWith: [
        "Read signalops://admin/summary first.",
        "Pull only the relevant read surfaces for the suspected issue domain: sequences, discovery summary, web resources, fetch runs, or LLM budget.",
      ],
      recommendedTools: {
        read: [
          "admin.summary.get",
          "llm_budget.summary",
          "web_resources.list",
          "web_resources.read",
          "fetch_runs.list",
          "sequences.list",
          "sequence_runs.list",
          "discovery.summary.get",
        ],
      },
      sessionFlow: [
        "Start broad with summary surfaces, then narrow to the affected entity or run.",
        "Prefer evidence collection first; only move into writes after the cause and desired change are clear.",
        "Use this scenario to prepare a human/operator explanation when the system is healthy but yield or usefulness is weak.",
      ],
      destructiveCautions: [
        "Observability work is read-only by default; switching into writes should be an explicit decision, not an accidental next step.",
      ],
      verifyAfterWrite: [
        "If the session escalates into a write, re-enter the relevant domain-specific scenario and verify there.",
      ],
    }),
  },
  {
    uri: "signalops://guide/scenarios/cleanup",
    name: "guide.scenarios.cleanup",
    description: "Concrete MCP playbook for safe cleanup after experiments, tests, and bounded operator changes.",
    mimeType: "application/json",
    read: async () => ({
      objective:
        "Use this scenario when a session created temporary sequences, channels, interests, templates, missions, or tokens that now need orderly cleanup without losing audit truth.",
      startWith: [
        "Read the affected entities first and decide which artifacts should remain for audit or acceptance evidence.",
        "Use admin.mcp_tokens.list/revoke/delete_revoked for MCP token inventory and lifecycle; do not call admin REST directly and do not guess raw database column names.",
        "Treat sequences with created_by starting migration: as protected system objects; do not archive them during cleanup.",
        "Use prompt cleanup.guidance when the cleanup spans more than one entity or mixes reversible and destructive actions.",
      ],
      recommendedTools: {
        read: [
          "admin.summary.get",
          "admin.mcp_tokens.list",
          "admin.mcp_tokens.revoke",
          "admin.mcp_tokens.delete_revoked",
          "sequences.read",
          "channels.read",
          "system_interests.read",
          "llm_templates.read",
          "discovery.artifacts.read",
          "discovery.source_inventory.read",
        ],
        write: [
          "sequences.archive",
          "system_interests.archive",
          "system_interests.delete",
          "llm_templates.archive",
          "llm_templates.delete",
          "channels.delete",
        ],
      },
      sessionFlow: [
        "Separate reversible cleanup from irreversible cleanup before calling any destructive tools.",
        "Prefer archive when the entity may still be useful as evidence, lineage, or rollback context.",
        "Archive only test/operator-created sequences; leave Default, Adaptive Discovery, Website Resource Extract, and other migration-owned sequences unchanged.",
        "Use delete only for clearly erroneous or intentionally disposable artifacts, and only with explicit confirmation.",
      ],
      destructiveCautions: [
        "Do not delete audit-relevant artifacts just to make the workspace look tidy.",
        "Re-confirm identifiers before destructive actions so cleanup does not hit the wrong entity.",
      ],
      verifyAfterWrite: [
        "Read the affected entities back and confirm the final lifecycle state matches the cleanup plan.",
      ],
      tokenInventoryNotes: {
        tool: "admin.mcp_tokens.list",
        databaseColumns: [
          "token_id",
          "label",
          "token_prefix",
          "scopes",
          "status",
          "issued_by_user_id",
          "revoked_by_user_id",
          "revoked_at",
          "expires_at",
          "last_used_at",
          "last_used_ip",
          "last_used_user_agent",
          "created_at",
          "updated_at",
        ],
        warning:
          "Raw SQL against mcp_access_tokens is not needed for normal MCP cleanup. If direct SQL is used during debugging, use these canonical column names; there are no id/name/is_active/is_revoked columns.",
      },
    }),
  },
];
